### PR TITLE
Transfer : Fix compatible transfers mapping: Closes #1060

### LINKED ISSUE #1060: Transfer : Fix compatible transfers mapping
Motivation
----------
The table mapping compatible mapping is erroneous 

Modification
------------
Fix the mapping table

### PR DESCRIPTION
**Pull request by cserf**
Transfer : Fix compatible transfers mapping: Closes #1060

### CODE REVIEW

**Comment by mlassnig** [comment]
We cannot do this, as this would block all transfers to Google until we have signed URL support in FTS. Suggest to put on hold.

**Comment by cserf** [comment]
Since more than 80 % of the sites have a WebDAV door, enabling S3 <-> davs  only would be enough.

**Comment by vingar** [comment]
To elaborate more on this: Introducing the distinction between stream and third party copy can be useful for the scheme mapping.

**Comment by bari12** [comment]
I don't think getting this stream information in there is particular useful. If we really need to regulate on this I would suggest to introduce a parameter in the conveyor-submitter where you can specify the protocol pairs the conveyor is allowed to use (or not allowed to use).

**Comment by cserf** [comment]
What can be done to regulate this is that the conveyor marks the non-matching protocol transfers, then it can release them slowly depending on how many transfers are already streaming through FTS.

**Comment by bari12** [comment]
That sounds a bit complicate for something which we should only use for integration/testing anyway. Maybe we can put these rules just in a highly throttled activity?

**Comment by vingar** [comment]
Do we need to know that we have stream party copy ? For example to limit them, be protected against, monitor ? If yes, a conveyor might have a flag to allow them or not and should be able to make the distinction between the two. If no, nothing needed :)

**Comment by mlassnig** [comment]
One other thing, FTS server will always go PULL->PUSH->STREAM, if either fails. We already might be streaming quite a bit.

**Review by mlassnig — APPROVED** [review]

**Comment by vingar** [comment]
@mlassnig you approved the change which removes the compatibility srm-s3. Is it expected ?

**Comment by mlassnig** [comment]
Yep, instead https/davs -> S3 was added, which is now supported by FTS.

**Pull request merged**
