### PR TITLE
core: update module dependencies. Fix #186

### PR DESCRIPTION
**Pull request by vingar**

### CODE REVIEW

**Comment by bari12** [comment]
Please rebase.

**Comment by vingar** [comment]
Flake8 errors (E722 do not use bare except) are due to the new flake8 version. Several options: We force this pull request, or we prepare later the migration to the new flake8 version and I removed it from this pull request

**Comment by bari12** [comment]
I would prefer to remove it from this pull request and do the new version upgrade + all fixes together. Otherwise this will just block us with the other pull requests.

**Comment by vingar** [comment]
#195 created to handle and prepare the migration to flake8-3.5.0

**Review by bari12 — APPROVED** [review]

**Pull request merged**
