### PR TITLE
Core: Change CMS permissions Fix #1005

### LINKED ISSUE #1005: Fix permissions for CMS
Motivation
----------
CMS has run into two problems with permissions:

1) A user cannot remove their own rules (ATLAS allows this).
2) Root cannot delete replicas. As long as PhEDEx is moving data under the hood for us, we think we need to be able to do this.

Modification
------------

### PR DESCRIPTION
**Pull request by ericvaandering**
This modifies the permissions for deleting a rule and deleting a replica to match what we think we need.

### CODE REVIEW

**Comment by ericvaandering** [comment]
@nataliaratnikova

**Comment by mlassnig** [comment]
it only failed on the code style check:

lib/rucio/core/permission/cms.py:312:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:313:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:314:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:344:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:345:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:346:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:378:23: W503 line break before binary operator
lib/rucio/core/permission/cms.py:379:23: W503 line break before binary operator
lib/rucio/core/permission/cms.py:380:23: W503 line break before binary operator
lib/rucio/core/permission/cms.py:570:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:571:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:572:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:573:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:574:13: W503 line break before binary operator

**Comment by ericvaandering** [comment]
Actually if you look at the latest pep-8 that’s preferable. :-)

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Mar 31, 2018, at 01:44, Mario Lassnig <notifications@github.com<mailto:notifications@github.com>> wrote:


it only failed on the code style check:

lib/rucio/core/permission/cms.py:312:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:313:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:314:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:344:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:345:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:346:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:378:23: W503 line break before binary operator
lib/rucio/core/permission/cms.py:379:23: W503 line break before binary operator
lib/rucio/core/permission/cms.py:380:23: W503 line break before binary operator
lib/rucio/core/permission/cms.py:570:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:571:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:572:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:573:13: W503 line break before binary operator
lib/rucio/core/permission/cms.py:574:13: W503 line break before binary operator

**Comment by mlassnig** [comment]
ok, guess we need a flake8 update ;-)

**Comment by vingar** [comment]
right, with the latest flake8 we have few E722 (bare excepts) errors that should be addressed before moving to it.

**Comment by vingar** [comment]
About the flake8 update:
Issue: #1012
PRs: #1013 #1014

Once approved and merged we can kick travis again on these PRs.

**Comment by bari12** [comment]
This will need a rebase for the pep8 changes.

**Comment by ericvaandering** [comment]
Rebased my two PRs

**Comment by bari12** [comment]
Hmm even with the new flake8 (3.5.0) and pep8 (1.7.1) this still brings the errors mentioned above.

**Comment by bari12** [comment]
We have to change to the new version of `pycodestyle==2.4.0` (formerly pep8) which actually checks to do it like eric did. #1039
However, we cannot do this right now as flake8 does not support pycodestyle==2.4.0 yet.
To make progress on this I would suggest @ericvaandering changes this to confirm to the current tests and we change this when we get pycodestyle==2.4.0 to work.

**Comment by ericvaandering** [comment]
Ok, I changed it. Please consider it for a merge when it comes back OK

**Comment by mlassnig** [comment]
Looks like Travis had a hiccup. I've restarted the build

**Review by mlassnig — APPROVED** [review]

**Pull request merged**
