### PR TITLE
Client: Pass forward x509 cert and key #6822

### PR DESCRIPTION
**Pull request by voetberg**
Add arguments for the x509 key, pass forward to the client auth

### CODE REVIEW

**Review by rdimaio — COMMENTED** [review]
LGTM - it would be great to also have a unit test to confirm this works correctly

**Comment by voetberg** [comment]
> LGTM - it would be great to also have a unit test to confirm this works correctly

Yeah totally agree - I think that would be a larger undertaking though. All of `test_bin_rucio` assumes auth has already taken place. (just with user/pass).

**Review by rdimaio — APPROVED** [review]

**Comment by rdimaio** [comment]
> > LGTM - it would be great to also have a unit test to confirm this works correctly
> 
> Yeah totally agree - I think that would be a larger undertaking though. All of `test_bin_rucio` assumes auth has already taken place. (just with user/pass).

I agree. I opened this issue to track creating tests for the auth methods: https://github.com/rucio/rucio/issues/6839, we can merge this first and then add tests as part of that issue

**Comment by dchristidis** [comment]
This PR introduced an annoying regression to `x509` authentication. The client reads from the configuration file only when `creds` is unset.

https://github.com/rucio/rucio/blob/0bbc069faf17f06eff1891aa90e634adea67b216/lib/rucio/client/baseclient.py#L264-L266

**Pull request merged**
