### PR TITLE
Testing: Add flake8-type-checking and move type-checking-only imports into TYPE_CHECKING blocks

### LINKED ISSUE #6728: Testing: Linter, add `flake8-type-checking`
Follow-up from: https://github.com/rucio/rucio/issues/6720, specifically this PR comment https://github.com/rucio/rucio/pull/6726#discussion_r1578962820

### PR DESCRIPTION
**Pull request by rdimaio**
Fixes #6728

### CODE REVIEW

**Comment by rdimaio** [comment]
Rebased in latest forcepush

**Comment by rdimaio** [comment]
Latest force-push: moved additional `type-checking-only` imports that were added from the rebase into `if TYPE_CHECKING` blocks

**Comment by rdimaio** [comment]
Rebased in latest force-push

**Comment by bari12** [comment]
Rebase please :-)

**Comment by rdimaio** [comment]
Rebased in latest forcepush

**Comment by rdimaio** [comment]
Rebased in latest force-push

**Comment by rdimaio** [comment]
Rebased and fixed linting issues in latest force-push

**Comment by rdimaio** [comment]
Rebased in latest forcepush

**Comment by rdimaio** [comment]
Fixed type-checking only import in latest revision

**Review by bari12 — APPROVED** [review]

**Pull request merged**
