### PR TITLE
Rewrite query for postgresql Fix #262

### LINKED ISSUE #262: db: fix outer join read lock for PostgreSQL
Motivation
----------
PostgreSQL is interpreting the SQL standard correctly, it's actually Oracle and MySQL which are doing non-standard things here. The problem you see is that for an outer join the nullable side cannot be locked for reading, so PostgreSQL stops. This is the last outstanding issue for PostgreSQL compatibility.

Modification
------------
Changing the query for add-rule from "select outer join for update" into something like "select for update union select".

Expected behavior
-----------------
add-rule will work on PostgreSQL.

### PR DESCRIPTION
**Pull request by vingar**

### CODE REVIEW

**Review by bari12 — COMMENTED** [review]
I don't think we should do it like this, as we don't know if that approach will work on scale well, it's too critical and too untested to just try it. I think for now the best thing to do is to have two different workflows based on the dialect. This we can merge without worrying and then maybe migrate to the workflow if we had proper time to test it on scale.

**Comment by vingar** [comment]
yes, I think also about doing the distinction by the dialect.  This approach is the one used in list_replicas...

**Comment by vingar** [comment]
if we can have the postgresql tests on travis, it would be good as we have few places with outer join+with update.

**Comment by bari12** [comment]
@tbeerman already implemented them; But we can only activate them once we made everything postgres compatible.

**Comment by vingar** [comment]
I need some help here. With docker on mac for postgresl it is very slow and I'm having some errors related to postgres. Where can we expose the result against postgres ?

**Comment by mlassnig** [comment]
I have it on my devbox, give me a sec.

**Comment by mlassnig** [comment]
Your branch against PSQL gives me:

Ran 397 tests in 246.378s
FAILED (errors=69, failures=19)


So, nothing really changed compared to before your branch ;-) I'm checking.... Eventually, all these errors and failures boil down to this single query, so a single fix will clean it all up.

**Comment by vingar** [comment]
could you expose the errors/failures somewhere ?  on docker, I'm still not getting the final output. The errors there looks not related to this query..e.g.,


CONVEYOR (DAEMON): Test the conveyor submitter daemon. ... /usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py:4230: SAWarning: Textual SQL expression "mod(abs(('x'||md5(rule_id..." should be explicitly declared as text("mod(abs(('x'||md5(rule_id...") (this warning may be suppressed after 10 occurrences)
  {"expr": util.ellipses_string(element)})
ok
ACCOUNT COUNTER (CORE): Increase, decrease and get counter ... ok
RSE COUNTER (CORE): Increase, decrease and get counter ... ok
ACCOUNT (CURL): Test whoami method ... FAIL
AUTH (CURL): Test auth token retrieval with via gss ... FAIL
AUTH (CURL): Test auth token retrieval with via username and password ... FAIL
AUTH (CURL): Test if token is valid ... FAIL
AUTH (CURL): Test auth token retrieval with via x509 ... FAIL
AUTH (CURL): Test auth token retrieval with via proxy ... FAIL
PING (CURL): Get Version ... ERROR
ACCOUNT (CURL): add account ... FAIL
RSE (CURL): add RSE ... FAIL
REPLICA (CLIENT): List dataset replicas. ... ERROR
REPLICA (CLIENT): List datasets in RSE. ... ERROR

**Comment by mlassnig** [comment]
it's all the same. most of the tests depend on datasets/files/ added which triggers add_rule, and then fail when the file is not found.

it's always like this (for different values of query parameters):


Details: (psycopg2.NotSupportedError) FOR UPDATE cannot be applied to the nullable side of an outer join
 [SQL: 'SELECT mlassnig.contents.child_scope AS mlassnig_contents_child_scope, mlassnig.contents.child_name AS mlassnig_contents_child_name, mlassnig.locks.scope AS mlassnig_locks_scope, mlassnig.locks.name AS mlassnig_locks_name, mlassnig.locks.rule_id AS mlassnig_locks_rule_id, mlassn
ig.locks.rse_id AS mlassnig_locks_rse_id, mlassnig.locks.account AS mlassnig_locks_account, mlassnig.locks.bytes AS mlassnig_locks_bytes, mlassnig.locks.state AS mlassnig_locks_state, mlassnig.locks.repair_cnt AS mlassnig_locks_repair_cnt, mlassnig.locks.updated_at AS mlassnig_locks_upd
ated_at, mlassnig.locks.created_at AS mlassnig_locks_created_at \nFROM mlassnig.contents LEFT OUTER JOIN mlassnig.locks ON mlassnig.contents.child_scope = mlassnig.locks.scope AND mlassnig.contents.child_name = mlassnig.locks.name AND mlassnig.locks.rse_id = %(rse_id_1)s \nWHERE mlassni
g.contents.scope = %(scope_1)s AND mlassnig.contents.name = %(name_1)s FOR UPDATE OF locks NOWAIT'] [parameters: {'rse_id_1': UUID('3c57fb4e-9fc5-49ef-8f9b-72348f4455fd'), 'name_1': 'dataset_8f54e34a36ca48fb9bc6ee47c161b5fb', 'scope_1': 'mock'}]

**Comment by vingar** [comment]
I found one place where the outer join + for update is called but apparently should be also at another place. @bari12 any hints ?

**Comment by bari12** [comment]
I think it should pretty much be only called from one method in rule.py. But this method is invoked by adding rules and evaluating rules, so pretty much touches many many workflows we have in rucio (adding dataset with rule etc.) - I will have a more detailed look later.

**Comment by vingar** [comment]
I got it:  get_files_and_replica_locks_of_dataset is in lock and replica  (with the same code) but can be called by rules with a different core module.

**Comment by vingar** [comment]
+ get_source_replicas_for_dataset in replicas

**Comment by vingar** [comment]
I managed to run  lib/rucio/tests/test_rule.py and got with the latest version: Ran 43 tests in 26.285s --> OK

**Comment by mlassnig** [comment]
running against my psql instance now, fingers crossed

**Comment by mlassnig** [comment]
great, can confirm that part is fixed. two psql bugs to go:

======================================================================
ERROR: DATA IDENTIFIERS (CORE): Delete dids
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/rucio/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/data/rucio/lib/rucio/tests/test_did.py", line 59, in test_delete_dids
    delete_dids(dids=dsns, account='root')
  File "/data/rucio/lib/rucio/db/sqla/session.py", line 358, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (psycopg2.ProgrammingError) column "did_type" is of type "CONTENTS_HIST_DID_TYPE_CHK" but expression is of type "CONTENTS_DID_TYPE_CHK"
LINE 1: ...tents.child_name AS mlassnig_contents_child_name, mlassnig.c...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
 [SQL: 'INSERT INTO mlassnig.contents_history (scope, name, child_scope, child_name, did_type, child_type, bytes, adler32, md5, guid, events, rule_evaluation, did_created_at, created_at, updated_at, deleted_at) SELECT mlassnig.contents.scope AS mlassnig_contents_scope, mlassnig.contents
.name AS mlassnig_contents_name, mlassnig.contents.child_scope AS mlassnig_contents_child_scope, mlassnig.contents.child_name AS mlassnig_contents_child_name, mlassnig.contents.did_type AS mlassnig_contents_did_type, mlassnig.contents.child_type AS mlassnig_contents_child_type, mlassnig
.contents.bytes AS mlassnig_contents_bytes, mlassnig.contents.adler32 AS mlassnig_contents_adler32, mlassnig.contents.md5 AS mlassnig_contents_md5, mlassnig.contents.guid AS mlassnig_contents_guid, mlassnig.contents.events AS mlassnig_contents_events, mlassnig.contents.rule_evaluation A
S mlassnig_contents_rule_evaluation, %(did_created_at)s AS did_created_at, mlassnig.contents.created_at AS mlassnig_contents_created_at, mlassnig.contents.updated_at AS mlassnig_contents_updated_at, %(deleted_at)s AS deleted_at \nFROM mlassnig.contents \nWHERE mlassnig.contents.scope =
%(scope_1)s AND mlassnig.contents.name = %(name_1)s'] [parameters: {'name_1': 'dsn_e5f9dea30240444484add6eea456adab', 'deleted_at': datetime.datetime(2017, 12, 4, 11, 43, 19, 814757), 'did_created_at': None, 'scope_1': 'mock'}]
-------------------- >> begin captured stdout << ---------------------
Data identifier not found.
Details: Data identifier 'archive:dsn_e5f9dea30240444484add6eea456adab' not found
(psycopg2.ProgrammingError) column "did_type" is of type "CONTENTS_HIST_DID_TYPE_CHK" but expression is of type "CONTENTS_DID_TYPE_CHK"
LINE 1: ...tents.child_name AS mlassnig_contents_child_name, mlassnig.c...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
 [SQL: 'INSERT INTO mlassnig.contents_history (scope, name, child_scope, child_name, did_type, child_type, bytes, adler32, md5, guid, events, rule_evaluation, did_created_at, created_at, updated_at, deleted_at) SELECT mlassnig.contents.scope AS mlassnig_contents_scope, mlassnig.contents
.name AS mlassnig_contents_name, mlassnig.contents.child_scope AS mlassnig_contents_child_scope, mlassnig.contents.child_name AS mlassnig_contents_child_name, mlassnig.contents.did_type AS mlassnig_contents_did_type, mlassnig.contents.child_type AS mlassnig_contents_child_type, mlassnig
.contents.bytes AS mlassnig_contents_bytes, mlassnig.contents.adler32 AS mlassnig_contents_adler32, mlassnig.contents.md5 AS mlassnig_contents_md5, mlassnig.contents.guid AS mlassnig_contents_guid, mlassnig.contents.events AS mlassnig_contents_events, mlassnig.contents.rule_evaluation A
S mlassnig_contents_rule_evaluation, %(did_created_at)s AS did_created_at, mlassnig.contents.created_at AS mlassnig_contents_created_at, mlassnig.contents.updated_at AS mlassnig_contents_updated_at, %(deleted_at)s AS deleted_at \nFROM mlassnig.contents \nWHERE mlassnig.contents.scope =
%(scope_1)s AND mlassnig.contents.name = %(name_1)s'] [parameters: {'name_1': 'dsn_e5f9dea30240444484add6eea456adab', 'deleted_at': datetime.datetime(2017, 12, 4, 11, 43, 19, 814757), 'did_created_at': None, 'scope_1': 'mock'}]

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: Removing did mock:dsn_e5f9dea30240444484add6eea456adab (DATASET)
--------------------- >> end captured logging << ---------------------


and


======================================================================
ERROR: SUBSCRIPTION (DAEMON): Test the transmogrifier and the split_rule mode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/rucio/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/data/rucio/lib/rucio/tests/test_subscription.py", line 335, in test_run_transmogrifier
    set_new_dids([{'scope': tmp_scope, 'name': dsn}, ], 1)
  File "/data/rucio/lib/rucio/db/sqla/session.py", line 349, in new_funct
    result = function(*args, **kwargs)
  File "/data/rucio/lib/rucio/core/did.py", line 797, in set_new_dids
    raise exception.DatabaseException('%s : Cannot update %s:%s' % (error.args[0], did['scope'], did['name']))
DatabaseException: Database exception.
Details: (psycopg2.ProgrammingError) column "is_new" is of type boolean but expression is of type integer
LINE 1: UPDATE mlassnig.dids SET is_new=1, updated_at='2017-12-04T11...
                                        ^
HINT:  You will need to rewrite or cast the expression.
 : Cannot update mock_497b8503:dataset-32f920d105b84a1289e1ad5ffaec5234

**Review by bari12 — APPROVED** [review]

**Pull request merged**
