### PR TITLE
Tests : Cleanup predefined RSEs first round : Fix #6212

### LINKED ISSUE #6212: Simplify the test pipeline
To run tests, we run a spaghetti of shell and python scripts with esoteric ways of passing parameters between them. It's very complex to actually run the tests locally. There is the donkeyrider, but it's just a wrapper to hide all the mess.

The goal of the ticket is to cleanup the test setup. Reduce the number of scripts. Make it possible to run the tests locally for every single database with minimal effort and using built-in capabilities rather than home-made wrappers. Idealy: be able to run one docker-compose command + one pytest command to execute tests for a selected database. All that without need for wrapper scripts.

### PR DESCRIPTION
**Pull request by cserf**
Tests : Cleanup predefined RSEs first round : Fix #6212

### CODE REVIEW

**Review by rcarpa — DISMISSED** [review]

**Comment by bari12** [comment]
🥳

**Comment by bari12** [comment]
There seem to be some errors with the multivo tests though? Any idea?

**Comment by rcarpa** [comment]
I think some tests are not very clean depend on the order of execution, even if they are not using predefined RSEs.

**Comment by bari12** [comment]
Rebase this please

**Review by bari12 — CHANGES_REQUESTED** [review]
Please rebase this

**Review by rcarpa — DISMISSED** [review]

**Review by bari12 — APPROVED** [review]

**Pull request merged**
