### PR TITLE
Core & Internals: Fix for Abacus Postgres Usage #6150

### PR DESCRIPTION
**Pull request by bjwhite-fnal**
Working on implementing the change described in the issue.

### CODE REVIEW

**Comment by bari12** [comment]
Note for myself: Needs backport to 1.29

**Comment by bari12** [comment]
@bjwhite-fnal please have a look on the tests. This doesn't work in our CI, possibly because the schema needs to be included in the queries?

**Comment by bjwhite-fnal** [comment]
Apologies, I pushed this trying to get it going right before going on vacation. I'll look at it again when I get back next week.

**Comment by bjwhite-fnal** [comment]
I need help fixing this from you guys please. Closing this.

**Pull request closed without merging**
