### PR TITLE
change travis oracle version to 12c #1307

### PR DESCRIPTION
**Pull request by tbeerman**
change travis oracle version to 12c #1307

### CODE REVIEW

**Review by vingar — DISMISSED** [review]
I remind that there are few other places with sleep statement. it would be good to have the same good approach than there. Reducing the sleep time to 10 can be considered too.

**Comment by tbeerman** [comment]
For Oracle 12c the sleep time of 30 should be ok. It anyway takes a couple of minutes to start up the container. For the other dbs it can be lower. 
This PR is still WIP and shouldn't be merged, yet. The tests haven't passed, yet. It shows green but the oracle test actually never ran and already failed with the DB initialization.  Furthermore, the Oracle test should be split into two different ones: one for 11g and one for 12c to make sure that the code remains backwards compatible.

**Comment by vingar** [comment]
One side comment: the json type support needs 12c and will fail with 11g. Meaning that the tests for 11g has to exclude them once merged.

**Review by vingar — DISMISSED** [review]

**Comment by tbeerman** [comment]
Please do not merge, the tests are still not running fine even though it showed green. Sometimes it works and sometimes it doesn't. It's not really stable. Before it just stalled during the tests and this time it failed to reset the DB. But the script still returns 0 so it looks like a success. That should be changed.

**Comment by bari12** [comment]
Yes, I noticed. I restarted the tests several times; One time it ran through green, without actually running all the tests due to some db connection timeout. Will leave it open.

**Pull request closed without merging**
