### PR TITLE
bb8: sql query ordered by file size - #1792

### PR DESCRIPTION
**Pull request by TomasJavurek**
bb8: sql query ordered by file size - 1792

### CODE REVIEW

**Comment by bari12** [comment]
It's good, but as a side comment, please mention the ticket with the `#` eg #1792, otherwise it is not clickable here 😄

**Comment by TomasJavurek** [comment]
yep, I noticed that only after commiting.

**Comment by mlassnig** [comment]
Looks ok to me, but I'm a bit worried that this is with raw SQL queries, instead of SQLAlchemy. Will this be changed eventually?

**Comment by bari12** [comment]
Yes should probably be changed eventually.

**Comment by TomasJavurek** [comment]
Interesting is, that although there was a bug in the code, and running it with python faild, travis didn't fail.

**Comment by bari12** [comment]
The BB8 test only covers a fraction of what BB8 actually does. So this was probably not covered by the test.

**Review by bari12 — APPROVED** [review]

**Pull request merged**
