### PR TITLE
Fix headers with new `add_header` script

### PR DESCRIPTION
**Pull request by joeldierkes**
Fixes the file headers with the new add_header script. Should be added after #5456 or as the only one

### CODE REVIEW

**Comment by bari12** [comment]
You are putting these `#!/usr/bin/env python3` shebang lines instead of the `#!/usr/bin/env python` ones. I was wondering if we should rather do this in a later step. If we want to cherry-pick this PR still to the `release-1.28` branch, then we need to keep some bins still on python(2).

**Comment by joeldierkes** [comment]
Yes, good idea. I'll change the script so that the same shebag line as present will be used.

**Comment by joeldierkes** [comment]
Done

**Comment by joeldierkes** [comment]
I can open a second PR for the master with only `python3` support if you'd like. We could also do that later.

**Review by bari12 — APPROVED** [review]

**Comment by bari12** [comment]
The second PR we can do when we do #5435

**Pull request merged**
