### PR TITLE
Core: add/inject_rule uses apply_rule, Fixes #3571

### LINKED ISSUE #3571: use sharded apply_rule in add/inject_rule
this (partly) addresses #3418 by limiting the amount of memory used during the transaction (usage is 20-30 KB per file!)

### PR DESCRIPTION
**Pull request by lgoossen**
Core: add/inject_rule uses apply_rule, Fixes #3571

### CODE REVIEW

**Comment by lgoossen** [comment]
first test round revealed indentation bug in rule_grouping.apply_rule
(code to update usage counters was indented 1 level too much and hence not executed for individual files)

**Review by mlassnig — DISMISSED** [review]
This looks OK to me, but I can't really test this. @bari12 ?

**Comment by bari12** [comment]
We are still working on the testing and deployment scheme of this; It would be quite risky to just put it into the code like this.

**Comment by lgoossen** [comment]
modified implementation allowing both old and new rule engine algorithm to be used
configuration switch is rules:use_new_rule_algorithm [False by default]
to allow nose tests to test both algorithms without config tampering, a module var USE_NEW_RULE_ALGORITHM
[False by default] can also be used to force the choice

**Review by bari12 — APPROVED** [review]

**Pull request merged**
