### PR TITLE
Testing: Print error logs in the integration test actions #5253

### LINKED ISSUE #5253: Print the integration test server logs in the actions
Motivation
----------
In #5249 the server logs were needed to track down an issue. We should print them by default to have more insight in case of a bug.

Modification
------------
Print the server logs when the integration tests are running in the actions. They should be printed after the test's run.

### PR DESCRIPTION
**Pull request by joeldierkes**

### CODE REVIEW

**Review by maany — DISMISSED** [review]
LGTM, thanks @joeldierkes. 

@bari12 please merge if CI passes ;)

**Comment by maany** [comment]
Damn, that's a lot of unrelated failing checks. Let's re-run and see what happens @joeldierkes ;)

**Comment by joeldierkes** [comment]
Yes, I already asked in the developer chat for help. This is already the second run...
I have no idea what is going on. It seems rather nondeterministic.

**Comment by maany** [comment]
As investigated by @joeldierkes and @rcarpa , we need to pin `itsdangerous` version in our requirements.

**Comment by joeldierkes** [comment]
We should also apply this feature to the 1.26 LTS release, it just changes the GitHub Action workflow

**Review by bari12 — APPROVED** [review]

**Pull request merged**
