### PR TITLE
Clients: ignore broken pipe. Closes #4482

### LINKED ISSUE #4482: The client should gracefully handle a broken pipe
Motivation
----------

```
$ rucio list-files data15_13TeV.00283270.physics_Main.recon.DRAW_ZMUMU.r9264_tid11227347_00 | head
+------------------------------------------------------+--------------------------------------+-------------+------------+----------+
| SCOPE:NAME                                           | GUID                                 | ADLER32     | FILESIZE   |   EVENTS |
|------------------------------------------------------+--------------------------------------+-------------+------------+----------|
| data15_13TeV:DRAW_ZMUMU.11227347._000001.pool.root.1 | 84388633-B329-E711-BDED-00266CF9479C | ad:b71b14d3 | 16.283 MB  |       18 |
| data15_13TeV:DRAW_ZMUMU.11227347._000002.pool.root.1 | 12D8B490-B329-E711-97BC-0CC47A7E6ADC | ad:d5c97d8c | 8.851 MB   |       10 |
| data15_13TeV:DRAW_ZMUMU.11227347._000003.pool.root.1 | EEC63F3C-B229-E711-827E-F04DA274CA37 | ad:4b56aed1 | 17.293 MB  |       19 |
| data15_13TeV:DRAW_ZMUMU.11227347._000004.pool.root.1 | D020E272-B129-E711-82E6-0CC47A7FC494 | ad:89a930fc | 4.885 MB   |        5 |
| data15_13TeV:DRAW_ZMUMU.11227347._000005.pool.root.1 | 7AC21392-B529-E711-8568-00266CF94824 | ad:8b91174b | 7.946 MB   |        8 |
| data15_13TeV:DRAW_ZMUMU.11227347._000006.pool.root.1 | 0E217900-B829-E711-B93D-00266CF94ACC | ad:cee56d1e | 9.605 MB   |       10 |
| data15_13TeV:DRAW_ZMUMU.11227347._000007.pool.root.1 | 3AE4312C-D529-E711-B879-F04DA274CA01 | ad:01fa8895 | 5.057 MB   |        5 |
2021-03-23 10:21:08,570 ERROR   [Errno 32] Broken pipe
2021-03-23 10:21:08,570 ERROR
Rucio exited with an unexpected/unknown error.
Please rerun the last command with the "-v" option to gather more information.
If it's a problem concerning your experiment or if you're unsure what to do, please followup at: hn-atlas-dist-analysis-help@cern.ch
If you're sure there is a problem with Rucio itself, please followup at: https://github.com/rucio/rucio/issues/
```

Modification
------------

### PR DESCRIPTION
**Pull request by rcarpa**
The second except block is probably only for the print at line 2403.

### CODE REVIEW

**Comment by bziemons** [comment]
Normally you should be handling `SIGPIPE` and closing all resources and exit your program on that signal (which in Python means calling `sys.exit` should be good enough). See [man 7 pipe](https://man7.org/linux/man-pages/man7/pipe.7.html)

**Comment by rcarpa** [comment]
I'm following the python's recommended way to handle this case : https://docs.python.org/3/library/signal.html#note-on-sigpipe

**Review by mlassnig — COMMENTED** [review]
Same needs to be done in `rucio-admin` ?

**Comment by rcarpa** [comment]
> Same needs to be done in `rucio-admin` ?

ah, true. Will add it.

**Review by mlassnig — APPROVED** [review]

**Pull request merged**
