### PR TITLE
web/rest/flaskapi/v1/ changed type to type_ #5208 to prevent overriding and better practice

### PR DESCRIPTION
**Pull request by pjflux2001**
type was conflicting with the type function(), and a bad practice too. Hence, I have modified the variable from type to type_.

### CODE REVIEW

**Comment by maany** [comment]
Hey @pjflux2001! Could you tell me why renaming type to type_ is necessary here? Is it conflicting with the built-in 'type' function?

**Comment by pjflux2001** [comment]
Yes, @maany it's conflicting with the type function(), and a bad practice too.

**Comment by mlassnig** [comment]
Hi Prashant, thanks for the PR. I've enabled the automatic tests.

**Comment by pjflux2001** [comment]
@mlassnig Thanks for enabling automatic tests. Both of the failing tests have nothing to do with my PR. Hence, I request you to merge them :smile:

**Comment by maany** [comment]
Hey @pjflux2001, the fixes for both of the failing tests are available in the master branch. If you rebase your PR, they should go away.
Also, please take a look at the [Contribution Guidelines](http://rucio.cern.ch/documentation/contributing/). In particular, 
1. create an issue describing what you intend to fix.
2. make sure your commit messages follow the guidelines as well.

**Comment by pjflux2001** [comment]
@maany @mlassnig I have made the required changes. Please re-run the workflows. Thanks

**Comment by maany** [comment]
@pjflux2001 None of the things I mentioned has been addressed. 

1. The master branch was `merged`, not `rebased`
2. The issue corresponding to this PR does not exist
3. The format of the commit message does not follow the one defined in the contribution guidelines.

Maybe it would be easier to close this PR, create the issue and send a new one that complies with the contribution guidelines.

**Pull request closed without merging**
