### PR TITLE
RSE Manager: implement lfns2pfns for posix. Fix #3395

### LINKED ISSUE #3395: Better handling of posix replica URLs
Motivation
----------

With `rucio.rse.protocols.posix.Default` implementation, the replicas with "file" schema always have port `0` in them, eg

`TEST1: file://:0/tmp/testfile`

Modification
------------

Override `lfns2pfns()` in the posix protocol.

I will submit a pull request for this shortly.

### PR DESCRIPTION
**Pull request by davidgcameron**
RSE Manager: implement lfns2pfns for posix. Fix #3395

### CODE REVIEW

**Comment by davidgcameron** [comment]
Anyone know why the tests are failing? I don't think it's related to my changes.

**Comment by mlassnig** [comment]
I restarted the jobs on Travis.

**Comment by davidgcameron** [comment]
I think these failures are actually related to the changes I made, since the MOCK RSE uses the posix protocol. When I try manually it also fails but with a different error

```
$ rucio-admin replicas declare-bad --reason test file:/tmp/test.2b27ab27-7f4a-4cc1-bca7-1fe257ef0b40
An unknown exception occurred.
Details: no error information passed (http status code: 404 ('not_found', '-o-'))
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/home/dcameron/dev/rucio-client-venv/bin/rucio-admin", line 129, in new_funct
    return function(*args, **kwargs)
  File "/home/dcameron/dev/rucio-client-venv/bin/rucio-admin", line 937, in declare_bad_file_replicas
    did_info = client.get_did(scope, name)
  File "/home/dcameron/dev/rucio-client-venv/lib/python3.6/site-packages/rucio/client/didclient.py", line 391, in get_did
    raise exc_cls(exc_msg)
rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 404 ('not_found', '-o-'))
```
In the server log:

`[Tue Mar 24 09:56:21.561737 2020] [core:info] [pid 183:tid 140611222001408] [client 213.55.244.2:40954] AH00026: found %2f (encoded '/') in URI (decoded='/dids/file//tmp/test.2b27ab27-7f4a-4cc1-bca7-1fe257ef0b40'), returning 404`

So something in declaring bad files doesn't handle file URLs.

**Comment by davidgcameron** [comment]
And I can recreate the test error using the client API:

```
>>> c.declare_bad_file_replicas(['file:/tmp/test.2b27ab27-7f4a-4cc1-bca7-1fe257ef0b40'], 'test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dcameron/dev/rucio-client-venv/lib/python3.6/site-packages/rucio/client/replicaclient.py", line 63, in declare_bad_file_replicas
    raise exc_cls(exc_msg)
rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '✗'))
```

Server log:

```
[Tue Mar 24 10:05:23.806768 2020] [:error] [pid 183:tid 140611238786816] (exceptions.ValueError) badly formed hexadecimal UUID string
[Tue Mar 24 10:05:23.806803 2020] [:error] [pid 183:tid 140611238786816] [SQL: SELECT rses.rse AS rses_rse
[Tue Mar 24 10:05:23.806807 2020] [:error] [pid 183:tid 140611238786816] FROM rses
[Tue Mar 24 10:05:23.806809 2020] [:error] [pid 183:tid 140611238786816] WHERE rses.id = %(id_1)s]
[Tue Mar 24 10:05:23.806815 2020] [:error] [pid 183:tid 140611238786816] [parameters: [{}]]
[Tue Mar 24 10:05:23.816523 2020] [:error] [pid 183:tid 140611238786816] Traceback (most recent call last):
[Tue Mar 24 10:05:23.816545 2020] [:error] [pid 183:tid 140611238786816]   File "/usr/lib/python2.7/site-packages/rucio/web/rest/replica.py", line 549, in POST
[Tue Mar 24 10:05:23.816548 2020] [:error] [pid 183:tid 140611238786816]     not_declared_files = declare_bad_file_replicas(pfns=pfns, reason=reason, issuer=ctx.env.get('issuer'))
[Tue Mar 24 10:05:23.816551 2020] [:error] [pid 183:tid 140611238786816]   File "/usr/lib/python2.7/site-packages/rucio/api/replica.py", line 83, in declare_bad_file_replicas
[Tue Mar 24 10:05:23.816554 2020] [:error] [pid 183:tid 140611238786816]     rse = get_rse_name(rse_id=k)
...
[Tue Mar 24 10:05:23.816670 2020] [:error] [pid 183:tid 140611238786816]   File "/usr/lib64/python2.7/uuid.py", line 134, in __init__
[Tue Mar 24 10:05:23.816673 2020] [:error] [pid 183:tid 140611238786816]     raise ValueError('badly formed hexadecimal UUID string')
[Tue Mar 24 10:05:23.816675 2020] [:error] [pid 183:tid 140611238786816] StatementError: (exceptions.ValueError) badly formed hexadecimal UUID string
[Tue Mar 24 10:05:23.816678 2020] [:error] [pid 183:tid 140611238786816] [SQL: SELECT rses.rse AS rses_rse
[Tue Mar 24 10:05:23.816680 2020] [:error] [pid 183:tid 140611238786816] FROM rses
[Tue Mar 24 10:05:23.816682 2020] [:error] [pid 183:tid 140611238786816] WHERE rses.id = %(id_1)s]
[Tue Mar 24 10:05:23.816684 2020] [:error] [pid 183:tid 140611238786816] [parameters: [{}]]
```

**Comment by davidgcameron** [comment]
Phew, finally found the problem. The MOCK RSEs in the tests are created with no hostname so they are assigned a default hostname 'localhost'. So I added the hostname to the URLs in lfns2pfns to handle this particular use case.

**Review by bari12 — APPROVED** [review]

**Pull request merged**
