### PR TITLE
Core & Internals: remove s3+rucio and s3+https protocols #2411

### PR DESCRIPTION
**Pull request by jamesp-epcc**
This change removes the legacy `s3+rucio` and `s3+https` protocols but I am not sure if this is all that should be done. Should the old `signeds3` and `s3es` protocols also be removed in favour of the URL signing support in the core? I think there may also need to be changes to the tests and scripts but I have opened this as a starting point for discussions.

### CODE REVIEW

**Comment by mlassnig** [comment]
adding @wguanicedew to confirm for EventService

**Comment by wguanicedew** [comment]
ok to remove them. They are not used.

**Review by bari12 — CHANGES_REQUESTED** [review]
Some flake8 errors
```
lib/rucio/web/rest/redirect.py:35:1: F401 'rucio.common.objectstore.connect' imported but unused
lib/rucio/web/rest/redirect.py:35:1: F401 'rucio.common.objectstore.get_signed_urls' imported but unused
lib/rucio/web/rest/redirect.py:285:37: F841 local variable 'selected_rse' is assigned to but never used
lib/rucio/web/rest/flaskapi/v1/redirect.py:33:1: F401 'rucio.common.objectstore.connect' imported but unused
lib/rucio/web/rest/flaskapi/v1/redirect.py:33:1: F401 'rucio.common.objectstore.get_signed_urls' imported but unused
lib/rucio/web/rest/flaskapi/v1/redirect.py:258:37: F841 local variable 'selected_rse' is assigned to but never used
lib/rucio/web/rest/flaskapi/v1/redirect.py:261:32: F821 undefined name 'signed_URLS'
lib/rucio/web/rest/webpy/v1/redirect.py:35:1: F401 'rucio.common.objectstore.connect' imported but unused
lib/rucio/web/rest/webpy/v1/redirect.py:35:1: F401 'rucio.common.objectstore.get_signed_urls' imported but unused
lib/rucio/web/rest/webpy/v1/redirect.py:285:37: F841 local variable 'selected_rse' is assigned to but never used
```

**Comment by jamesp-epcc** [comment]
I have now removed a lot more of the legacy code (possibly too much, please let me know if so!). Once I got started it made more sense to take it all out at once due to interdependencies. The Travis check failed, but only the Postgres tests. Nothing I have done should be sensitive to the database, so I'm not sure if this is a genuine failure or just a problem with the tests.

**Comment by jamesp-epcc** [comment]
Closed and reopened to get Travis checks to rerun, it passed the second time.

**Review by mlassnig — APPROVED** [review]
this looks good to me. second pair of eyes @bari12 ?

**Review by bari12 — APPROVED** [review]

**Pull request merged**
