### PR TITLE
update db/sqla to sqlAlchemy 2;  session manage using future=true; 2.…

### PR DESCRIPTION
**Pull request by yuyiguo**
update db/sqla to sqlAlchemy 2;  session manage using future=true; 2.0 sql and code reformat using VSC.
Deprecated method replaces the Engine.has_table() method with inspector.has_table().
scoped_session with python context manage issuse: https://github.com/sqlalchemy/sqlalchemy/issues/6519 .

### CODE REVIEW

**Comment by bari12** [comment]
I think you are using a code-formatter (black?) here which makes this very hard to review. It basically looks like everything is being changed, while most of it is just formatting?
I know this is hard now, but please submit this without the formatting changes. This would also just dilute git blame/log.
Thanks 👍

**Comment by rcarpa** [comment]
Code formatting changes must not be submitted in the same commit as functional changes. This PR is impossible to review. 

I'm forced to ask you to update your PR to only include the functional changes without any formatting updates.

If you consider that the new formatting is better and merits a discussion/merge into rucio, you can submit it in a separate PR, which only does formatting update and no other changes. However, be prepared for a harsh opposition. From me included.

**Comment by yuyiguo** [comment]
I use visual studio code that is configured with LSST python code format requirements, but these are just some basic stuff. It is Ok for me to check out a fresh version from github and apply the changes in vim. I will submit a new PR.

**Comment by rcarpa** [comment]
There should probably be a way to tell vscode to avoid reformatting the code in a specific project.

**Comment by yuyiguo** [comment]
A newer [PR ](https://github.com/rucio/rucio/pull/5872/commits/3048a84a0a8bdba16139dba0fc356e1897d6f36d)replaced this one.

**Pull request closed without merging**
