### PR TITLE
Clients: Clients: disable certification verification on s3 boto protocol

### PR DESCRIPTION
**Pull request by wguanicedew**
To fix the ssl verification problem on centos7 machines

### CODE REVIEW

**Comment by mlassnig** [comment]
This completely disables SSL remote server verification. Is this what we want?

**Review by bbockelm — CHANGES_REQUESTED** [review]
Seems to almost definitely be the wrong approach. I don’t think security should be sacrificed even as a convenient work-around.  These things have a way of being embedded and forgotten for years.

**Comment by wguanicedew** [comment]
S3 boto is using S3_ACCESS_KEY and S3_SECRET_KEY to verify connections. It's not using proxy to verify.

**Comment by bbockelm** [comment]
I think it uses `S3_ACCESS_KEY` and `S3_SECRET_KEY` to authorize the connection.  Authentication of the remote server (as well as the integrity and secrecy of the channel) are based on TLS still.

**Pull request closed without merging**
