### PR TITLE
Lowercase rse rule

### PR DESCRIPTION
**Pull request by ericvaandering**
Pull request title
------------------

The format of the Pull request title must be:

    <component>: <short_change_message> #<issue number>

If you add a [github-recognised keyword](https://help.github.com/articles/closing-issues-using-keywords/) then
the associated issue can be closed automatically once the pull request is merged, e.g.::

    <component>: <short_change_message> Fix #<issue number>

Valid component names are listed in the `label list <https://github.com/rucio/rucio/labels>`_.

### CODE REVIEW

**Comment by ericvaandering** [comment]
What did I do wrong here? I have a single commit that is branched off of next that I requested to be merged to master. Should I rebase to fork off of master instead? Or make a 2nd PR by cherry-picking?

**Comment by vingar** [comment]
did you push from the same branch to next and master ?

**Comment by ericvaandering** [comment]
Yes. There is one branch, it started from next. Should I start my branch from the "hottest" branch instead (master in this case)?

**Comment by ericvaandering** [comment]
Fixes #554

**Review by mlassnig — CHANGES_REQUESTED** [review]
your master was out of sync at the time of branching, can you please stash, git reset --hard and do it again?

**Comment by ericvaandering** [comment]
@mlassnig you didn't actually request changes, right? Just the rebase which is now done.

**Pull request merged**
