### PR TITLE
Remove hardcoded Belle II permission, schema, algorithms, and move VO test to use the policy package

### LINKED ISSUE #7157: Extraction of Belle II logic to policy package
Part of https://github.com/rucio/rucio/issues/4798

### PR DESCRIPTION
**Pull request by rdimaio**
Fixes #7157

### CODE REVIEW

**Comment by rdimaio** [comment]
Temp policy package repo for reference https://github.com/rucio/temporary-belle2-policy-package

**Comment by rdimaio** [comment]
Latest revision: rebase, fix merge conflict

**Comment by rdimaio** [comment]
latest revision: rebase, fix merge conflict

**Review by bari12 — APPROVED** [review]

**Comment by dchristidis** [comment]
Was `unified-atlas-tape-metadata-colocation.patch` purposefully included?

**Comment by rdimaio** [comment]
> Was `unified-atlas-tape-metadata-colocation.patch` purposefully included?

it wasn't, good catch. Removing now, it was a temporary patch that got through by mistake when rebasing

**Comment by rdimaio** [comment]
https://github.com/rucio/rucio/pull/7192

**Pull request merged**
