### PR TITLE
Add ATLAS policy package to ATLAS VO test, remove ATLAS schema and permission from core repository

### LINKED ISSUE #6962: Move ATLAS VO test to use policy package

### PR DESCRIPTION
**Pull request by rdimaio**
Fixes #6962

### CODE REVIEW

**Comment by rdimaio** [comment]
Additionally - we use the ATLAS permission and schema in the end-to-end tests and autotests as well. We should probably not do that and instead use the generic permission and schema, but in the meantime those have also been modified to use the ATLAS policy package instead of the deleted hardcoded ATLAS permission and schema

**Review by bari12 — APPROVED** [review]

**Comment by voetberg** [comment]
@maany 
Heads up - this breaks the dev envs as given by instructions [here](https://rucio.cern.ch/documentation/developer/setting_up_vscode_dev_env) - the requirements.txt used here isn't the dev one so it misses the atlas_test_policy install.

**Comment by rdimaio** [comment]
> @maany Heads up - this breaks the dev envs as given by instructions [here](https://rucio.cern.ch/documentation/developer/setting_up_vscode_dev_env) - the requirements.txt used here isn't the dev one so it misses the atlas_test_policy install.

Looking through https://github.com/maany/rucio-vscode-dev-env, it uses the docker.io/rucio/rucio-dev image as base: https://github.com/maany/rucio-vscode-dev-env/blob/main/Dockerfile#L2C6-L2C31

Which installs `requirements.dev.txt` if found:

https://github.com/rucio/containers/blob/a1c44109c3f8c6813da25f19f82e01239fcb97eb/dev/Dockerfile#L75-L85

Which contains the policy package:

https://github.com/rucio/rucio/blob/bab14b94d990546f66399c202e72e597834ec0af/requirements/requirements.dev.txt#L42-L43

If it's related to the issue that James was seeing yesterday, that's related to this https://github.com/rucio/rucio/issues/7082

**Comment by voetberg** [comment]
Not sure what issue James saw (I may not be in the right channel), so I have no idea if it's the same. Only thing I know was that rebasing broke my dev env and re-installing it didn't fix it because of the testing policy package :(

**Comment by rdimaio** [comment]
> Not sure what issue James saw (I may not be in the right channel), so I have no idea if it's the same. Only thing I know was that rebasing broke my dev env and re-installing it didn't fix it because of the testing policy package :(

My bad - it was Alexander that saw an issue, not James (and it was a DM, so it wasn't in any channel).

This is the error message he saw:

```
Traceback (most recent call last):
  File "/opt/rucio/tools/reset_database.py", line 25, in <module>
    from rucio.db.sqla.util import build_database, create_base_vo, create_root_account, destroy_database, drop_everything  # noqa: E402
  File "/usr/local/lib/python3.9/site-packages/rucio/db/sqla/util.py", line 36, in <module>
    from rucio.common.schema import get_schema_value
  File "/usr/local/lib/python3.9/site-packages/rucio/common/schema/__init__.py", line 49, in <module>
    check_policy_package_version(POLICY)
  File "/usr/local/lib/python3.9/site-packages/rucio/common/utils.py", line 2119, in check_policy_package_version
    raise PolicyPackageVersionError(package)
rucio.common.exception.PolicyPackageVersionError: Policy package atlas_rucio_policy_package is not compatible with this Rucio version
Failed to reset the database!
```

Do you have the same error message in your dev environment?

**Pull request merged**
