### PR TITLE
Core & Internals: respect add_dids permissions on replica creation. Closes #6058

### LINKED ISSUE #6058: rucio upload does not check that the user has permission to add DIDs
### Description

When a user uploads new files to Rucio using the `rucio upload` command, new DIDs are created in the Rucio database for the files. However, this is done using an `add_replicas` call, which adds the DIDs directly to the database table (in `core/replica.py:__bulk_add_new_file_dids`). Because `add_did`/`add_dids` is never called, the permission check for `add_did` is also never called. This is a problem for DUNE as we are using a custom `add_did` permission check to prevent users from adding files that are not present in DUNE's metadata catalogue.

### Steps to reproduce

1. Modify permissions so that the current user is not allowed to add new DIDs (or change the permission code so that the `add_did` and `add_dids` checks always fail).
2. Perform a `rucio upload` to add a new file.
3. Observe that the upload succeeds and a new DID is created.

### Rucio Version

1.29

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by rdimaio**
Follow-up from this PR: https://github.com/rucio/rucio/pull/6332

The commits here are exactly the same as that PR, rebased with the latest changes with conflicts resolved.

### CODE REVIEW

**Comment by bari12** [comment]
Rebase plz :-)

**Comment by rdimaio** [comment]
Rebased in latest forcepush

**Comment by bari12** [comment]
Please rebase again

**Comment by rdimaio** [comment]
Tests still failing (https://github.com/rdimaio/rucio/actions/runs/9892852445) - I think it'd be best to split this in separate PRs, as there's a few different things going on here (some commits removing unused functions, another one changing functionality: https://github.com/rucio/rucio/pull/6686/commits/8b1db582769fbf963ec56c96a0f06f4cec9d5d66)

Will pick this back up after we merge some other PRs that touch the same files. Keeping it open for reference until then

**Comment by rdimaio** [comment]
Closing in favour of separate PRs.
PR 1: https://github.com/rucio/rucio/pull/6960
PR 2: https://github.com/rucio/rucio/pull/6979

**Pull request closed without merging**
