### PR TITLE
probes: lost files double counts - #2104

### PR DESCRIPTION
**Pull request by TomasJavurek**
probes: lost files double counts - #2104

### CODE REVIEW

**Comment by cserf** [comment]
Looks good, but can you make it py3k compatible ?

**Comment by bari12** [comment]
Ping @TomasJavurek

**Comment by TomasJavurek** [comment]
Pong @bari12

**Comment by TomasJavurek** [comment]
Well the error says:
No module named 'retrying'
but that seems more like problem with pip install, or venv, than py3k, right?

**Comment by bari12** [comment]
What Cedric means is making the file PY3K ready. You can for example use `pylint --py3k` to check what's wrong. print statements for example.

**Pull request merged**
