### PR TITLE
db: boolean handling

### PR DESCRIPTION
**Pull request by mlassnig**
db: boolean handling

### CODE REVIEW

**Comment by bari12** [comment]
I am not quite sure how the `tmp_atlas_` variables help? I still see a problem with this when we are in the INT / PROD inconsistency we will have for a week?
Also I wonder if we should add an upgrade script where we change all the True/False to true/false?

**Comment by mlassnig** [comment]
We need a third "truth" state for the RSEs, which is represented by the tmp_atlas variables. That's why they are twice handled: once in the core, and once on the DB type.

Script: Alembic doesn't support content updates, would have to go through the SQLAlchemy interface. There's no way to downgrade though anymore, because that would update all "true" to "True", when they would only partially be "True" before.

Maybe it's better to just provide a SQL statement with the upgrade instructions?

**Comment by bari12** [comment]
We should still add an alembic update file here (if possible) which changes `False/True` to `false/true`. We should also add a note to the release which clarifies that entries with `0/1` which are used as boolean (Thus not `tier` etc.), should also be changed to `false/true`

**Comment by vingar** [comment]
I'm wondering if won't help to introduce some extra column with the right type directly or a column describing the type and the constraint. e.g; json schema.  Something like : atr, value , schema or description. 

The schema field can thus be used to convert the value to the right type, without touching the current value and be backward compatible.

**Comment by bari12** [comment]
Pylint throws some errors here

```
E: 40, 4: Module 'alembic.op' has no 'execute' member (no-member)
E: 41, 4: Module 'alembic.op' has no 'execute' member (no-member)
E: 42, 4: Module 'alembic.op' has no 'execute' member (no-member)
E: 43, 4: Module 'alembic.op' has no 'execute' member (no-member)
E: 62, 4: Module 'alembic.op' has no 'execute' member (no-member)
E: 63, 4: Module 'alembic.op' has no 'execute' member (no-member)
E: 64, 4: Module 'alembic.op' has no 'execute' member (no-member)
E: 65, 4: Module 'alembic.op' has no 'execute' member (no-member)
```

**Comment by mlassnig** [comment]
hmmm, seems like pylint does not properly resolve the alembic imports?

**Comment by bari12** [comment]
Yes, this happens sometimes. `# pylint: disable=no-member` is your friend 😄

**Comment by bari12** [comment]
Please rebase to make tests work.

**Comment by mlassnig** [comment]
@bari12 we basically need to have this running in production before we can merge https://github.com/rucio/rucio/pull/2031 , otherwise we will have to make another workaround to deal with 0/1 in list_rses

**Review by bari12 — APPROVED** [review]

**Pull request merged**
