### PR TITLE
Documentation: Fixes grammatical errors in api.rst Fix #935

### LINKED ISSUE #935: Typo in Client API reference
Motivation
----------
Grammatical error in the client API reference documentation.
In the file api.rst

Modification
------------

### PR DESCRIPTION
**Pull request by nawedx**
Documentation: Fixes grammatical errors in api.rst Fix #935

### CODE REVIEW

**Review by mlassnig — APPROVED** [review]

**Comment by bari12** [comment]
Hi @nawedx 
Please rebase this with upstream/master. Sometimes the travis checks are not started due to a conflict which can be resolved with a rebase. This seems to be the case here.

**Comment by vingar** [comment]
up

**Comment by nawedx** [comment]
Hi @bari12 
How do I rebase with upstream master?

**Comment by mlassnig** [comment]
``get fetch --all``
``get rebase upstream/master``
``git push --force``

**Comment by nawedx** [comment]
Thanks @mlassnig . I have executed those commands.

**Comment by mlassnig** [comment]
@nawedx are you sure the git push worked? i don't see any update here on github

**Comment by nawedx** [comment]
@mlassnig when I executed git push, it asked for username and password.
`[nawedx@jam rucio]$ git fetch --all
Fetching origin
Fetching upstream
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 19 (delta 13), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (19/19), done.
From https://github.com/rucio/rucio
   4d2ecedb..1e0d95f7  master     -> upstream/master
   619868c3..28e53160  next       -> upstream/next
[nawedx@jam rucio]$ git rebase upsream/master
fatal: Needed a single revision
invalid upstream upsream/master
[nawedx@jam rucio]$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to upstream/master.
[nawedx@jam rucio]$ git push --force
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (15/15), 2.34 KiB | 599.00 KiB/s, done.
Total 15 (delta 11), reused 0 (delta 0)
remote: Resolving deltas: 100% (11/11), completed with 10 local objects.
To https://github.com/nawedx/rucio.git
   4d2ecedb..1e0d95f7  master -> master
`

**Comment by bari12** [comment]
Closing; Please submit again.

**Pull request closed without merging**
