### PR TITLE
Clients: xrange to range #819

### PR DESCRIPTION
**Pull request by jwackito**
Clients: xrange to range #819

### CODE REVIEW

**Comment by vingar** [comment]
```
$ grep -r xrange lib/rucio/common/
lib/rucio/common//utils.py:    for i in xrange(0, len(l), n):
lib/rucio/common//utils.py:    for dummy in xrange(retries):
$ grep -r xrange lib/rucio/client/
lib/rucio/client//downloadclient.py:        for dummy in xrange(retries):
```

**Comment by jwackito** [comment]
Not touching lib/rucio/clients yet.. should I?
I'm only changing bin/ files...

**Comment by vingar** [comment]
your choice ;) but they are part of the clients so now or later ...

**Comment by jwackito** [comment]
There is a couple of them for print too
rucio/client/dq2client.py:                print rule
rucio/client/dq2client.py:                    print 'Error'
rucio/client/fileclient.py:            print r.status_code
rucio/client/lifetimeclient.py:        print render_json(**data)
rucio/client/lifetimeclient.py:        print result.text
I will do them later...

**Comment by vingar** [comment]
to be precise, those directories are shipped with the clients:
rucio/client
rucio/common
rucio/rse/
rucio/rse/protocols
rucio/tests

**Comment by bari12** [comment]
Yup, all of them need to be changed in the end :)

**Comment by jwackito** [comment]
I'll take care of them... one folder/pull request at the time...

**Review by vingar — APPROVED** [review]

**Pull request merged**
