### PR TITLE
Transmogrifier improvements : Closes #5624, #5600, #5599, #5564

### LINKED ISSUE #5564: Subscriptions should support maxizing the number of copies based on the RSE expression
Motivation
----------

One might want to have a subscription that creates rules for each RSE matching some expression. Currently, it is necessary to manually calculate the number of RSEs matching an expression and statically set the number of copies. It would be preferable if there’s some special value like `*` or `-1` which is automatically replaced with the number of RSEs at the time the rule is created.

Modification
------------

Note that such a feature might be useful to have wherever rules are being created e.g. `rucio add-rule foo:bar '*' 'tier=1&type=DATADISK'`.

### LINKED ISSUE #5599: Support overriding the account of replication rules produced by subscriptions
Motivation
----------

https://github.com/rucio/rucio/blob/b8e5795c5065a5d493cf9e4088169ddd48c26b3a/lib/rucio/daemons/transmogrifier/transmogrifier.py#L293

Modification
------------

If `account` is specified in a `replication_rule` definition, then said rule should be created with that account.

### LINKED ISSUE #5600: Support delayed injection for rules produced by subscriptions
Motivation
----------

One might want the rule created by a subscription to not ‘activate’ until some point in the future.

Modification
------------

Parse and make use of a `delay_injection` parameter.

### LINKED ISSUE #5624: Transmogrifier code restructing
Motivation
----------
Transmogrifier main function is monolithic. Code needs restructing

### PR DESCRIPTION
**Pull request by cserf**
This PR is fixing multiple issues :
- Transmogrifier code restructuring. Cut the monolithic main function into smaller bits. Closes : https://github.com/rucio/rucio/issues/5624
- Support injection of delayed rules. Closes : https://github.com/rucio/rucio/issues/5600
- Overriding the subscription account if an account is specified into replication rules : Closes https://github.com/rucio/rucio/issues/5599
- Support of wildcard for argument `copies` to create as many copies of RSEs under a specific RSE expression : Closes : https://github.com/rucio/rucio/issues/5564
- Introduce tests that were missing for some functionalities (e.g. chained subscriptions)

### CODE REVIEW

**Comment by rcarpa** [comment]
The first commit is extremely difficult to review. It mixes new functionality; with code move; with refactoring; and code formatter visual changes.

**Comment by bari12** [comment]
I have to agree with Radu, this is very hard to review since it is really unclear what changed and what was just hit by the code formatter. Although we don't have a guideline/rule here, I find this "irregular" application of code formatters bothersome - this is a discussion we need to have. In any way, the application of the formatter should be broken into a separate commit.

**Comment by cserf** [comment]
Just to clarify. There is no **additional code formatting** in the 1st commit. The code was already formatted before (see https://github.com/rucio/rucio/commit/cbb5a31d1ad9dcb82aad65d4a2cbb628b9f7d779). This is just a massive restructuring of the code and there is nothing that is coming from `black`. Now I get the argument from Radu and next time I will try to do smaller changes.

**Comment by bari12** [comment]
Thanks Cedric, I will add it for 1.29.1

**Comment by bari12** [comment]
Please rebase this

**Comment by cserf** [comment]
@bari12 Code was rebased

**Review by bari12 — APPROVED** [review]

**Pull request merged**
