### PR TITLE
Testing: Add type hints to utils.py and FilterEngine, refactoring code where needed

### PR DESCRIPTION
**Pull request by rdimaio**
Part of #6588.

## b3227b10292f523726fcc0cee0afce24f681a738

- The `BaseClient` constructor is refactored in a way where the static type checker can detect that `host` and `auth_host` are never `None`.

## d5d3d6751f1e0dc74b86325064de466ede45fa87

- Type annotations in `utils.py`. The methods here are used in a few places, and there are some instances where the input types are unclear, so I added `type: ignore` comments in places where the issue seems to be with the parent function rather than the util function. Some notes below.

### `oidc.py`

```
- 1 errors with message """Argument of type "str | Unknown | Any" cannot be assigned to parameter "vallist" of type "list[str]" in function "val_to_space_sep_str"

  Type "str | Unknown | Any" cannot be assigned to type "list[str]"

    "str" is incompatible with "list[str]"""".

Candidates: line 1277
```

### `filter_engine.py`

```
- 3 errors with message """Cannot access member "append" for type "dict[str, Any]"

  Member "append" is unknown""".

Candidates: line 284, 341, 422
```

## 4d2808d044735451d908405f794ddb1298ccbe73
- The linter complains about `re.match(str(cfg_forced_modules), module_name)` if `module_name` is `None`.

## 3fee6f75234bc5075d7fb99e79cf9a74a0c41256
- The changes here are due to adding type hints to the util function `parse_did_filter_from_string_fe` in `utils.py`, which is then called in `FilterEngine`. I added type hints all around to make it easier to understand which types were being passed in `FilterEngine`, as well as refactoring some stuff where needed for type hinting purposes.

### CODE REVIEW

**Review by bari12 — DISMISSED** [review]

**Comment by bari12** [comment]
Please rebase

**Comment by rdimaio** [comment]
Rebased in latest force-push

**Comment by rdimaio** [comment]
Latest force-push:
- fixes an issue that arose from fixing a merge conflict
-  removing deprecated type `Type` to comply with the linter

**Comment by rdimaio** [comment]
Latest forcepush: fixed two issues that arose from the rebase that I had missed

**Review by bari12 — DISMISSED** [review]

**Comment by bari12** [comment]
Rebase please :-)

**Comment by rdimaio** [comment]
Rebased in latest force-push

**Review by bari12 — APPROVED** [review]

**Pull request merged**
