### PR TITLE
clients: Import extra modules only if they are available Fix #336

### LINKED ISSUE #336: Import extra modules only if they are available
Motivation
----------
Some modules are not necessary in the clients and should be imported only if available or installed in the environment

Modification
------------
* Define a list of extra packages, check for their presence and import them if there
* Add a new exception missingModuleException and raise it from the method which can not worked with the missing module

### PR DESCRIPTION
**Pull request by vingar**

### CODE REVIEW

**Comment by mlassnig** [comment]
Lots of "ValueError: No JSON object could be decoded" which points to a server error? Looks unrelated to the patch. I'm restarting the CI.

**Comment by vingar** [comment]
it should be because of missing dependencies which should go in the main requirements files now as they are optional in the clients

**Comment by vingar** [comment]
one test failing against postgresql, weird 
======================================================================
FAIL: DATA IDENTIFIERS (CLIENT): List dids by pattern.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/rucio/lib/rucio/tests/test_did.py", line 187, in test_list_dids
    assert_equal(len(results), 2)
AssertionError: 3 != 2

**Comment by bari12** [comment]
I have restarted the tests here too, lets see if it helps.

**Comment by bari12** [comment]
Ok now its a bunch of pylint/flake output. Did somebody change the tests scripts?

**Comment by vingar** [comment]
I moved the flake8/pylint tests at the beginning as it's faster to get those check first. 
If the pylint output is there it means that there is one pylint error somewhere

**Comment by bari12** [comment]
Hmm I don't see that change in the changed files. Also we would need that on master as well then.

**Review by bari12 — APPROVED** [review]

**Pull request merged**
