### PR TITLE
Transfers: modification to Rucio QoS workflow #5968

### PR DESCRIPTION
**Pull request by maatthias**
Removing copy_pin_lifetime from the transfers_to_create dictionaries.

### CODE REVIEW

**Review by bari12 — CHANGES_REQUESTED** [review]
You need to remove it in L1020 as well.

**Comment by maatthias** [comment]
In testing this a bit more I think we need to keep L1020.  This handles the case when there is no replica at destination.  Which as I understand we need when it's a transfer and not a stagein.  What do you think?

**Comment by bari12** [comment]
I don't think it will work, because the `copy_pin_lifetime` will be enforced at the source, it's always enforced on the source. And the source might very well be a disk...

**Comment by maatthias** [comment]
Yes I see your point but it also renders the tests useless (they will always fail) as they're currently written.  To rewrite to test a pass we are effectively forcing the copy_pin_lifetime pass, the request to be DONE and the rule OK and not really testing any transitions.  Which isn't testing anything :)  I will remove the unit tests, make this change and do a push.

**Comment by bari12** [comment]
Hmm, I don't think I follow/agree 😄 
You are right that `test_transfer_to_mas_new_replica` and `test_failed_transfer_to_mas_new_replica` doesn't test anything which is not already tested. (Since we can't set a pin at destination)
But the other two `test_transfer_to_mas_existing_replica` and `test_failed_transfers_to_mas_existing_replica` are correct, these test the stagein from the tape.

**Comment by maatthias** [comment]
Yes indeed you are right.  Those tests are valid when we remove the initial check that the request has the copy_pin_lifetime (they do not because the replica doesn't exist yet.)  The second check is the test we want.  I just pushed the changes.

**Comment by maatthias** [comment]
@bari12 can this be merged?  That `git cherry pick` seems unrelated to the code change and typing requirements, yes?

**Comment by maatthias** [comment]
@bari12 I ran into merge conflicts squashing the commits here.  Perhaps it was all of the fork syncs going back a few months.  Pushed a clean branch and new [pull request](https://github.com/rucio/rucio/pull/6079)  If that's OK I'll close this one.

**Pull request closed without merging**
