### PR TITLE
Clients: add config option for default metadata plugin #4825

### PR DESCRIPTION
**Pull request by davidgcameron**

### CODE REVIEW

**Comment by davidgcameron** [comment]
How should the new parameter be documented? Add manually to [configuration parameters](https://rucio.cern.ch/documentation/configuration-parameters), or is that auto-generated from something else?

**Comment by maany** [comment]
Hey @davidgcameron 
For the failing CI test/s, could you decorate them with `@pytest.mark.dirty` or `pytest.mark.noparallel` for now. ( example: https://github.com/rucio/rucio/pull/4819/commits/7207e31084427ad8b4833fa11b9719275e43876d)
@bziemons @rcarpa do we have a plan to resolve these tests for good?

**Comment by rcarpa** [comment]
> Hey @davidgcameron
> For the failing CI test/s, could you decorate them with `@pytest.mark.dirty` or `pytest.mark.noparallel` for now. ( example: [7207e31](https://github.com/rucio/rucio/commit/7207e31084427ad8b4833fa11b9719275e43876d))
> @bziemons @rcarpa do we have a plan to resolve these tests for good?

The tests where rock stable for weeks. The instability comes from some recently merged PR. We should obviously find the problem and fix it. But I don't understand the blaming :) It's everbody's responsibility to keep parallel tests working correctly :grin:

**Comment by maany** [comment]
> > Hey @davidgcameron
> > For the failing CI test/s, could you decorate them with `@pytest.mark.dirty` or `pytest.mark.noparallel` for now. ( example: [7207e31](https://github.com/rucio/rucio/commit/7207e31084427ad8b4833fa11b9719275e43876d))
> > @bziemons @rcarpa do we have a plan to resolve these tests for good?
> 
> The tests where rock stable for weeks. The instability comes from some recently merged PR. We should obviously find the problem and fix it. But I don't understand the blaming :) It's everbody's responsibility to keep parallel tests working correctly 😁

@rcarpa noted :D 
No blaming at all and I agree it is everyone's responsibility to keep the tests rock solid ;) 

 I just wanted to be looped in with the latest status as I was not following the tests closely. Sorry if it sounded the wrong way, it was not the intention. I would actually like to assist any efforts in the testing field and was curious to know your thoughts or any ongoing work where I could jump in ;)

**Comment by cserf** [comment]
I think you should blame me, since the test failing is mine. To my defense, it was not failing when my PR was merged : https://github.com/rucio/rucio/pull/4517 (the failing one is the cherry picking test)

**Review by bari12 — APPROVED** [review]

**Pull request merged**
