### PR TITLE
Clients: fixed empty result for list dids with meta comand; Fix #2403

### LINKED ISSUE #2403: ineffective `list-dids-by-meta`
Motivation
----------

````
bash-4.2# rucio get-did-meta  manda:manda-5_hours.tar
key3: 1.23
key2: 123
key1: value1
````
but: 
```
bash-4.2# rucio list-dids-by-meta --scope  manda key3=1.23
bash-4.2# rucio list-dids-by-meta  key3=1.23 
bash-4.2# 
```

### PR DESCRIPTION
**Pull request by hahahannes**
Clients: fixed empty result for list dids with meta comand; Fix #2403

### CODE REVIEW

**Comment by hahahannes** [comment]
Wanted to add this test, but I am getting a database error that the datatime columns are missing. So I added `Versioned` to the class in models.py but it does not change while running the tests.
```python
def test_list_dids_by_meta(self):
    """ CLIENT(USER): list dids by metadata search."""
    scope = 'mock'
    name = generate_uuid()
    key = generate_uuid()
    meta = {key: 'test'}
    self.did_client.add_dataset(scope, name)
    self.did_client.add_did_meta(scope, name, meta)
    cmd = 'rucio list-dids-by-meta --scope {0} {1}={2}'.format(scope, key, meta[key])
    exitcode, out, err = execute(cmd)
    nose.tools.assert_not_equal(re.search('{0}:{1}'.format(scope, name), err), None)
```

**Review by mlassnig — COMMENTED** [review]
hmmm, we actually wanted to get rid of "Versioned" and have explicit history tables

**Comment by mlassnig** [comment]
Ah, wait, that looks unrelated. which datetime column is causing problems? ModelBase already provides `created_at` and `updated_at`

**Comment by hahahannes** [comment]
`updated_at` is causing the problem. 
Also occurs on `rucio add-did-meta  --did mock:rucio --key bla --value test`.
```
"Unknown column 'did_meta.updated_at' in 'field list'") [SQL: u'SELECT did_meta.scope AS did_meta_scope, did_meta.name AS did_meta_name, did_meta.meta AS did_meta_meta, did_meta.updated_at AS did_meta_updated_at, did_meta.created_at AS did_meta_created_at \nFROM did_meta \nWHERE did_meta.scope = %s AND did_meta.name = %s'
```

**Comment by bari12** [comment]
The `Versioned` is unrelated. Please remove (as this would also inject a history table)

To me it seems that the issue here is the ` _oracle_json_constraint` event listener, which somehow prevents the generation of the updated_at/created_at.

**Review by mlassnig — APPROVED** [review]

**Comment by bari12** [comment]
> Wanted to add this test, but I am getting a database error that the datatime columns are missing. So I added `Versioned` to the class in models.py but it does not change while running the tests.
> 
> ```python
> def test_list_dids_by_meta(self):
>     """ CLIENT(USER): list dids by metadata search."""
>     scope = 'mock'
>     name = generate_uuid()
>     key = generate_uuid()
>     meta = {key: 'test'}
>     self.did_client.add_dataset(scope, name)
>     self.did_client.add_did_meta(scope, name, meta)
>     cmd = 'rucio list-dids-by-meta --scope {0} {1}={2}'.format(scope, key, meta[key])
>     exitcode, out, err = execute(cmd)
>     nose.tools.assert_not_equal(re.search('{0}:{1}'.format(scope, name), err), None)
> ```

We should still try to figure out why this one doesn't work. @hahahannes can you please address this in a separate issue.

**Pull request merged**
