### PR TITLE
storm, gfal, downloadclient: adding logging - #3472

### PR DESCRIPTION
**Pull request by TomasJavurek**
storm, gfal, downloadclient: adding logging - #3472

### CODE REVIEW

**Review by mlassnig — COMMENTED** [review]
this looks ok to me. second patch will come with actual logging messages or will you update this one?

@TWAtGH eyes pls

**Comment by TomasJavurek** [comment]
> this looks ok to me. second patch will come with actual logging messages or will you update this one?

We will add the logging messages in the individual protocols when they will be needed. For now, I added just one to the storm, that serves as a check that it really gets into the pilot log. This was requested by @davidgcameron

**Comment by davidgcameron** [comment]
Please add the check that the link exists after it was created, and feel free to be as verbose as possible in these logs. For example:

Creating link from x -> y
Created link from x-> y
Checking link x exists
Output of stat(x)
Link exists ok

**Comment by TomasJavurek** [comment]
> Please add the check that the link exists after it was created, and feel free to be as verbose as possible in these logs. For example:
> 
> Creating link from x -> y
> Created link from x-> y
> Checking link x exists
> Output of stat(x)
> Link exists ok

Right. I would do it step by step. Let's firstly get the logs into the protocols. Checking the link is different issue/suggestion. A good one, but I'll make separate ticket for that.

**Review by bari12 — APPROVED** [review]

**Pull request merged**
