### PR TITLE
Core: staging_area replicas including in file replica list and used as transfer source; closes #2069

### LINKED ISSUE #2069: Allow staging_area replicas to be used as transfer sources and include them in the list replicas output
Motivation
----------

Staging area replicas should be available for use as transfer sources and appear in the replica list. This makes the staging area behave more like a "virtual disk"

Modification
------------

Drop the staging_area==False restrictions on the queries.

### PR DESCRIPTION
**Pull request by illingwo**
Core: staging_area replicas including in file replica list and used as transfer source; closes #2069

### CODE REVIEW

**Comment by mlassnig** [comment]
For me this is fine, but I'm not sure if there's some implication that I'm overseeing. @cserf , opinion?

**Comment by illingwo** [comment]
As far as I know I'm the only one trying to use the staging area, which limits the potential issues if there are any problems. It's not something that's likely to get triggered accidentally.

**Comment by bari12** [comment]
I think this should be fine too. We are handling the staging_areas in a very specific way due to the workflow we had in ATLAS back in the days; But there is no special reason in locking it exactly to this way, so I think this change is fine.
However, I won't merge this into 1.19.0 as I am already preparing the release. @illingwo I would suggest to close this and re-submit as a patch, so we can have it in 1.19.1.

**Comment by illingwo** [comment]
There's a (trivial) merge conflict with the current master; I think it'll be simpler to wait until you've merged next in before resubmitting it.

**Pull request closed without merging**
