### PR TITLE
Hermes2 : Add a protection against empty transferred_at : Closes #4618

### LINKED ISSUE #4618: Hermes2: Add a protection against empty transferred_at
Motivation
----------
When someone cancels a transfer, `transferred_at` is not set which crashes hermes2 if it works on influx.

### PR DESCRIPTION
**Pull request by cserf**
Hermes2 : Add a protection against empty transferred_at : Closes #4618

### CODE REVIEW

**Comment by cserf** [comment]
The fix is line 341 ;)

**Review by mlassnig — APPROVED** [review]
You and your spaces before ":"

:-p

**Comment by bari12** [comment]
I think we should make a decision about the spaces before `:` once and for all. I don't even mind so much the spaces (Although I prefer not to have them), but mostly I care about the consistency/inconsistency through the code. It just makes the logs harder to read and with everything pushed to elastic, also harder to filter for.

Will add a discussion point for this to the next Dev meeting, so we setup a style guide for this.

**Comment by bari12** [comment]
In the meanwhile I will merge, since it was like this before already anyway 👍 😄

**Pull request merged**
