### PR TITLE
Patch 6159 checks for available replicas

### PR DESCRIPTION
**Pull request by ivukotic**
VP replicas should be delivered only when there is an available replica that is not on the TAPE.
This change just adds a condition that the replica is AVAILABLE.

### CODE REVIEW

**Review by dchristidis — CHANGES_REQUESTED** [review]
Thanks for bearing with me. This is better, but note quite there yet.

* There are three commits, changing about 30 lines. This should be a single commit, only adding two lines.
* The commit message format is proper, but the message itself could be improved (e.g. `Replicas: skip unavailable datasets for VP; Fix #6159`).

**Comment by ivukotic** [comment]
> Thanks for bearing with me. This is better, but note quite there yet.
> 
> * There are three commits, changing about 30 lines. This should be a single commit, only adding two lines.
> * The commit message format is proper, but the message itself could be improved (e.g. `Replicas: skip unavailable datasets for VP; Fix #6159`).

now done as requested

**Review by dchristidis — CHANGES_REQUESTED** [review]
This PR now has four commits.

**Comment by ivukotic** [comment]
is that a problem? we just do squash merge and it will be one...

**Comment by dchristidis** [comment]
Yes, it’s a problem (otherwise I would not have asked!) We use the ‘rebase and merge’ strategy, which would mean that all four commits go into the history.

**Comment by ivukotic** [comment]
so what would you like me to do? close this PR and create a new one?

**Comment by dchristidis** [comment]
No, a new PR won’t be necessary. You can rebase and fix the issue locally and then force-push.

**Comment by ivukotic** [comment]
this got very messed up. will close this one and create a new one

**Comment by ivukotic** [comment]
Hi,

Rebase went horribly wrong, so I deleted that PR and created a new one:
https://github.com/rucio/rucio/pull/6174

Ilija

**Pull request closed without merging**
