### PR TITLE
Tests: Update test_rucio_bin to use fixtures, #6529

### PR DESCRIPTION
**Pull request by voetberg**
Near re-write of `test_rucio_bin` to change the hard-coding to fixtures and temp_factories. Extension of #6531 

Tried to leave functionality unchanged.

### CODE REVIEW

**Comment by bari12** [comment]
I think this is a good idea. @rdimaio can you please have a look as well.

**Comment by rdimaio** [comment]
> I think this is a good idea. @rdimaio can you please have a look as well.

It's marked as draft - @voetberg is it ready for review? Feel free to mark it as ready in that case

**Comment by voetberg** [comment]
@rdimaio That's right it is a draft - I was having some issues getting everything to pass again so put this on the back-burner.

**Comment by voetberg** [comment]
Need to solve the mystery of why the multivo non-auto oidc auth tests are failing, but I do not expect that to change the PR contents dramatically

**Pull request closed without merging**
