### PR TITLE
Documentation: Fixed rse_expressions filename in RSE overview Fix #808

### LINKED ISSUE #808: RSE_Expressions link broken in documentation
Motivation
----------
Following the [RSE Expressions](http://rucio.readthedocs.io/RSE_Expressions.html) on http://rucio.readthedocs.io/overview_Rucio_Storage_Element.html leads to a non-existing page.

Modification
------------
Either the link in https://github.com/rucio/rucio/blob/master/doc/source/overview_Rucio_Storage_Element.rst needs to be made lower-case or the file https://github.com/rucio/rucio/blob/master/doc/source/rse_expressions.rst needs to be renamed to `RSE_Expressions`.

### PR DESCRIPTION
**Pull request by kreczko**
Fixing issue #808.

I mostly wanted to try out the tools for making patches, but `tools/submit-pull-request` is not working for me (not Python 3 compatible).
A patch for that is available [here](https://gist.github.com/kreczko/57cfa4752aa47143e7cdeb49d2007ffd) if you are interested, but it is also missing the `commands` module so I left it at replacing `print`.

### CODE REVIEW

**Comment by mlassnig** [comment]
Hi Luke, thanks for your patch!

I can confirm that you py3 patch works for our production infrastructure (py 2.6.6), so I would suggest you "git commit --amend" your patch and have it included so everyone can benefit.

**Comment by bari12** [comment]
Since this is a patch, please also open a second Pull Request against the next branch. 😄

**Comment by kreczko** [comment]
@bari12 Thanks, will do.

**Comment by bari12** [comment]
Hi @kreczko, The PR against `master` was correct, what I meant is create a second PR against `next`.  I know the fact that we have two separate PR (which are the same) against two branches is a bit confusing. https://github.com/rucio/rucio/blob/master/CONTRIBUTING.rst explains a little bit why we do that; Essentially we want to expose problems at the earliest possible points in the development chain, that's why we make PR against both branches.

**Comment by kreczko** [comment]
@bari12 Thanks, I should have read more carefully :).

**Review by bari12 — APPROVED** [review]

**Pull request merged**
