### PR TITLE
tests: Attempt to speed up tests by --processes=2

### PR DESCRIPTION
**Pull request by vingar**

### CODE REVIEW

**Comment by mlassnig** [comment]
On my dev-node I got an improvement from 362 to 361 seconds ;-)

**Comment by bari12** [comment]
On Travis:  Ran for 40 min 51 sec 😄

**Comment by vingar** [comment]
The parameter was at the wrong place and now it fails. From the errors, it looks like apache is configured to have only one session and all tests are waiting for it.  
@tbeerman, Is it correct ?

**Comment by bari12** [comment]
I think this can be closed? The changes to the AUTHORS file should be done in a separate PR.

**Pull request closed without merging**
