### PR TITLE
WebUI: added DID tracking; Fix #2637

### LINKED ISSUE #2637: Tracking what happened to a did
Motivation
----------
A way to track (visualise) what happened to a did.
- Check historic information
- Transfers
- etc.

### PR DESCRIPTION
**Pull request by hahahannes**
WebUI: added DID tracking; Fix #2637

### CODE REVIEW

**Comment by mlassnig** [comment]
@hahahannes @tbeerman what do we do with this patch? :-)

**Comment by hahahannes** [comment]
I would merge it :D 

It was supposed to add some kind of visual tracking. I have added a table with timestamps and actions and a scrollable plot. But I guess the plot is not that important and adds quite a lot of third party code

**Comment by bari12** [comment]
WebUI changes we can always be a bit bold since this won't break something massively anyway. But it would still be good if @tbeerman could check it, it has barely been 8 month though 🤣

**Comment by tbeerman** [comment]
I've tried this locally and it would need some changes. I got it to work for some DIDs but for others the timeline is just blank. I couldn't really figure out what the problem was, though.

**Comment by bari12** [comment]
Closing this. Apologies @hahahannes for the work, but currently there is nobody maintaining this code so it is a bit too risky to add this new complexity to the ui.

**Comment by hahahannes** [comment]
No problem. I could work on it, if it is still needed. Probably just some endpoint changes.

**Pull request closed without merging**
