### PR TITLE
documentation: operator cleanup

### PR DESCRIPTION
**Pull request by mlassnig**
documentation: operator cleanup

### CODE REVIEW

**Comment by cserf** [comment]
He... Why did you remove cli_admin_examples.rst and cli_examples.rst ?

**Comment by mlassnig** [comment]
aren't they replaced by this new man/rucio-admin.rst and man/rucio.rst thing?

look here: http://mario-dev.cern.ch/rucio/

**Comment by cserf** [comment]
Unfortunately argarse-sphinx doesn't print the examples written in the epilog in the subparser...

**Comment by vingar** [comment]
it might be possible to add the generation of the epilog in the argarse parser

**Comment by bari12** [comment]
@mlassnig Are you still changing anything here, can this be merged?

**Comment by mlassnig** [comment]
can be merged from my side

**Comment by vingar** [comment]
@bari12 we need an issue about cli_admin_examples.rst and cli_examples.rst,  argarse-sphinx etc

**Comment by bari12** [comment]
It's mentioned in our main documentation tracking ticket #572 
This will also be partly in #551

**Review by bari12 — APPROVED** [review]

**Pull request merged**
