### PR TITLE
Clean-up unneeded RSEs + Start introducing rse_factory in tests : Closes #5499

### LINKED ISSUE #5499: Cleanup unneeded RSEs in sync_rses.py
Motivation
----------
In `sync_rses.py` a lot of RSEs are defined but not used anywhere. They need to be cleaned. Moreover, some of the RSEs do not match the schema from some VOs. Naming needs to be fixed.
Longer term is to move everything to `rse_factory`

### PR DESCRIPTION
**Pull request by cserf**
Tests : Cleanup unneeded RSEs in sync_rses.py #5499 

- Remove unneeded RSEs
- Start moving to `rse_factory` in a few tests `test_dids`, `test_subscriptions`, etc.

### CODE REVIEW

**Comment by cserf** [comment]
Need rebase when https://github.com/rucio/rucio/pull/5525 is merged

**Review by rcarpa — DISMISSED** [review]

**Comment by bari12** [comment]
@cserf I think there are some tests related to this PR failing

**Comment by maany** [comment]
@bari12 I need to look why the integration tests are failing ( and where are they exactly creating the mock-rse's from)

**Comment by cserf** [comment]
All tests are fixed now, except the integration-tests

**Comment by rcarpa** [comment]
That integration test workflow is very complex. I would bet it uses an old version of rse_repository.json from the master or container rather than using the one from the current commit.

**Comment by rcarpa** [comment]
Probably this one : https://github.com/rucio/containers/blob/master/dev/rse_repository.json

**Comment by cserf** [comment]
I see. Would it be possible to update the json file ? If we remove the RSEs before this PR is merged, all the other tests will fail, so maybe what can be done is just add the new `SSH-DISK` to begin with, then when the PR is merged, the RSEs can be removed and we ask people to rebase their open PR.

**Comment by rcarpa** [comment]
yes, probably duplicating the RSE is the best solution. I'm not 100% sure the issue comes from there howether.

**Comment by cserf** [comment]
Rebase

**Comment by cserf** [comment]
Once all the tests succeed, this PR needs to be merged asap, otherwise the integration tests will fail for the other PRs.

**Review by bari12 — APPROVED** [review]

**Pull request merged**
