### PR TITLE
Fixed minor typos in Documentation

### PR DESCRIPTION
**Pull request by viveknigam3003**
Pull request title
------------------

The format of the Pull request title must be:

    <component>: <short_change_message> #<issue number>

If you add a [github-recognised keyword](https://help.github.com/articles/closing-issues-using-keywords/) then
the associated issue can be closed automatically once the pull request is merged, e.g.::

    <component>: <short_change_message> Fix #<issue number>

Valid component names are listed in the `label list <https://github.com/rucio/rucio/labels>`_.

### CODE REVIEW

**Comment by bari12** [comment]
Hi @viveknigam3003 
Please check the [Contribution guide](https://github.com/rucio/rucio/blob/master/CONTRIBUTING.rst) for the PR workflow.
Martin

**Comment by bari12** [comment]
Hi @viveknigam3003 
Both your PRs are still not compliant to the contribution guide. Please read especially **step 4** and re-submit. I'll close them now.
Cheers,
Martin

**Comment by viveknigam3003** [comment]
Sir,
I'm extremely sorry for that, but I think maybe I'm not able to understand
the instructions accurately. I'll try reading it more carefully and create
another PR.

Regards,
Vivek Nigam

**Comment by bari12** [comment]
No worries 😄 you can also ask on Slack if you have any questions.

**Pull request closed without merging**
