### PR TITLE
Core & Internals: get_submitted_at_rucio Fix #232

### LINKED ISSUE #232: get_submitted_at_rucio should return an array of submitted_at time stamps
Motivation
----------
get_submitted_at_rucio function in forecast.py extension is buggy. 

Modification
------------
The function have access to rucio database, but the query is tricky and need testing on production to see if the time to retrieve the submitted_at time stamps for a link in not an overkill.

Expected behavior
-----------------
Should return an array on time stamps ordered descendent (the oldest one at the end).

### PR DESCRIPTION
**Pull request by jwackito**
Core & Internals: get_submitted_at_rucio Fix #232

### CODE REVIEW

**Comment by bari12** [comment]
Hmm travis fails, is this related to #246? @cserf @tbeerman

**Comment by tbeerman** [comment]
Yes, @cserf changed the base docker image in #246 to already install the Oracle instantclient. In the docker build of travis it then also tries to install the client but it is already there and yum returns with an non-zero exit code, which breaks the build.

**Comment by mlassnig** [comment]
I'm wondering if all these rse2site-like methods wouldn't be a better fit for common/util.py ?

**Comment by vingar** [comment]
site is a rse attribute and the core methods related to rse_attributes are in in core/rse.  There are already some code duplication between the methods in core/rse and the rse2site methods.  If it is needed for the clients, I would rather put them in rse.clients

**Comment by mlassnig** [comment]
@bari12 feel free to undo my approve if you want @jwackito to externalise the site/rse methods beforehand

**Review by mlassnig — APPROVED** [review]

**Pull request merged**
