### PR TITLE
Remove MySQL5 support; Fix #4646

### LINKED ISSUE #4646: Remove MySQL 5 support
Motivation
----------

As agreed some time ago, remove MySQL 5 workarounds and clean up codebase.

### PR DESCRIPTION
**Pull request by mlassnig**

### CODE REVIEW

**Comment by rcarpa** [comment]
It's unfortunate that the update of unrelated headers was included in the same commit as the functional changes. It makes the review more complex.

**Comment by mlassnig** [comment]
Yeah, I was running the header update on the whole thing, because otherwise I wouldn't have touched it anyway. Sorry about that.

**Review by bziemons — APPROVED** [review]
lgtm, but shouldn't have been a patch

**Review by bziemons — CHANGES_REQUESTED** [review]
although.. the mysql8 tests are hanging and failing

**Comment by mlassnig** [comment]
I'll redo this as a feature

**Pull request closed without merging**
