### PR TITLE
Nearly final schema and permissions for CMS

### PR DESCRIPTION
**Pull request by ericvaandering**
These have been living in our repository as we transition. They can go back into Rucio nowf

### CODE REVIEW

**Comment by bari12** [comment]
Hi @ericvaandering 
Please have a look on the tests :-)

**Comment by ericvaandering** [comment]
OK. I don't get why the webpy tests, etc are failing. Do I need to worry about that?

**Comment by bari12** [comment]
I think these are tests failing in lib/rucio/tests/test_schema_cms.py

**Comment by ericvaandering** [comment]
OK, errors fixed.

**Review by bari12 — APPROVED** [review]

**Pull request merged**
