### PR TITLE
Core & Internals: added rse expression to resolve all RSEs; Fix #1455

### LINKED ISSUE #1455: Handling of istape=False in the client
Motivation
----------
Currently, the clients only allow downloads from RSEs which are flagged with `istape=False`. There are two issues with this. For some reason, in ATLAS, the `istape` attribute has been stored with the value `"False"` instead of the value `0`, which means the rse_expression only works with the direct string check on `"False"`. Secondly, as this is hardcoded in the client, for communities which do not have their RSEs flagged with `"istape=False"` the download will not work.
We need a better workflow for this.

Some options are:
- Extending the RSE Expression parameter with a system-default `*` parameter, which lists all RSEs. Currently, in ATLAS, the `ALL` flag is used for this, but again, this needs to be created by a script. A system internal parameter would be good. With this a new attribute could be used to flag tape rses: `tape=1`. The client can now do the download with the EXPRESSION `*\tape=1`. Even for communities who do not have the tape flag, this query will work.

### PR DESCRIPTION
**Pull request by hahahannes**
Core & Internals: added rse expression to resolve all RSEs; Fix #1455

### CODE REVIEW

**Comment by hahahannes** [comment]
I think we need another name for the new tape attribute because '\t' is used for tabs and this causes problems with the regex, if I got it correctly.
```python
from rucio.core.rse_expression_parser import parse_expression
parse_expression('rse=MOCK\istape=1') # correct output
parse_expression('rse=MOCK\tape=1') # Expression does not comply to RSE Expression syntax
```

**Comment by bari12** [comment]
Should be fine to just escape the backslash. `\\`

**Comment by hahahannes** [comment]
Ah yes, this works. Should I change or do we use the old attribute?

**Comment by bari12** [comment]
I would leave it like it is at the moment. I am not sure if the new attribute is consistently set yet.

**Comment by mlassnig** [comment]
Can confirm that we use `istape` all over the place

**Comment by bari12** [comment]
Can you please add the new `*` operator in the documentation about RSE Expressions as well. Could be useful also for other queries.

**Review by bari12 — APPROVED** [review]

**Pull request merged**
