### PR TITLE
WebUI: Fix misinterpretation of the date picker #4184

### LINKED ISSUE #4184: Suspicious replicas page is misinterpreting the date picker
Motivation
----------

The code expects the return string from the date picker to be in `DD/MM/YYYY` format but it’s actually in `MM/DD/YYYY`.

Modification
------------

Swap the array indices.

### PR DESCRIPTION
**Pull request by dchristidis**

### CODE REVIEW

**Review by mlassnig — DISMISSED** [review]
this is .... o.O

**Comment by bziemons** [comment]
seems suspicious to me since date -> str functions in JavaScript are locale-controlled and this might be switched in FR/EN 
sure about this change?

**Comment by mlassnig** [comment]
On my default Firefox (US), it creates this for December 7:

`https://rucio-ui.cern.ch:443/proxy/replicas/suspicious/?rse_expression=tier=1&younger_than=2020-07-12T00:00:00&nattempts=10`

If I change my browser language and locale to DE, it creates `2020-07-12` still.

**Comment by mlassnig** [comment]
This forces the locale for the datepicker, regardless what the browser wants. See here: https://api.jqueryui.com/datepicker/#method-option

**Comment by bziemons** [comment]
it will return the date as `2020-12-24` though, so split by `-` instead of `/`, see https://jqueryui.com/datepicker/#date-formats

Edit: split is not needed anymore instead, which is even better

**Comment by bari12** [comment]
Ping, what's the status here?

**Comment by dchristidis** [comment]
I’ll come back to this after things calm down. :D

**Comment by bari12** [comment]
Another ping 🛎️ 😄

**Comment by dchristidis** [comment]
Replaced with #4556 (patch instead of feature).

**Pull request closed without merging**
