### PR TITLE
Clients: expose replicalocks to the client #2112

### PR DESCRIPTION
**Pull request by dciangot**
Clients: expose replicalocks to the client #2112

### CODE REVIEW

**Comment by bari12** [comment]
Hi @dciangot 
PR is good, can you please just rebase this with `next`. The `next` branch was failing due to another issue which was just fixed.

**Comment by dciangot** [comment]
mmm, rebased. But please check if this was the result you meant ^^

**Comment by bari12** [comment]
Hmm, somehow this looks like it pulled in a lot of (valid) commits, but this might just be a github display issue, since the PR was based on a different commit before - but it's hard to review this now. Can you please close and re-submit the PR, let's see if this fixes it 😄

**Comment by dciangot** [comment]
Yes, I was kind of suggesting it with my question ^^

**Comment by dciangot** [comment]
@bari12 please find the new PR here: https://github.com/rucio/rucio/pull/2289

**Pull request closed without merging**
