### PR TITLE
Add TestPolicyPackageVersion, and other refactoring

### PR DESCRIPTION
**Pull request by rdimaio**
Main changes:
- [Refactor translation classes to a separate file](https://github.com/rucio/rucio/commit/f6dbb6023f56af6ce2e7b4bdd19053fcae7377d4)
- [Add TestPolicyPackageVersion](https://github.com/rucio/rucio/commit/060203b0b886faa26971733eb1be33fc4edb5712) https://github.com/rucio/rucio/issues/7008
- [Refactor client-related utils functions into common/client](https://github.com/rucio/rucio/commit/5fbd31de340ce242f79397689e3ec12d809258d9)

The `ligo_rucio` type error was a pre-existing error in `RSEDeterministicTranslation`. Pyright fails to detect the `pylint: disable=import-error` comment and expects `type: ignore` instead, but `Pylint` fails in the opposite case.

### CODE REVIEW

**Comment by rdimaio** [comment]
Rebased in latest forcepush

**Comment by rdimaio** [comment]
Fix linting error in latest push

**Comment by rdimaio** [comment]
Rebased in latest forcepush

**Comment by rdimaio** [comment]
Fix arguments of PolicyPackageBaseException-based exceptions (was previously working but then removed due to https://github.com/rucio/rucio/issues/7066) in latest forcepush

**Comment by rdimaio** [comment]
Latest revision: moved `from rucio.common.types import LoggerFunction` under the same `TYPE_CHECKING` as `from collections.abc import Callable` (they were under two separate blocks previously, I think I didn't see the first block when I was working on this)

**Review by bari12 — APPROVED** [review]

**Pull request merged**
