### PR TITLE
Fix id/id_ and some PEP-8 issues

### PR DESCRIPTION
**Pull request by ericvaandering**

### CODE REVIEW

**Comment by bari12** [comment]
Hi @ericvaandering 
If you are still developing this, please close the PR and submit it once done. I know it's just a draft, but each commit submission takes runner slots away from the CI which delays everything else. You can just let the GH actions run in your private repository (Just push to your origin) and you get exactly the same test runs as here. Thanks

**Comment by ericvaandering** [comment]
Closing to be kind to the CI

**Comment by ericvaandering** [comment]
OK, this is now working and I'd like to get it merged. As you can see from the comments I lifted a very useful function from kronos.py so I'd propose to refactor this. It seems to me lib/common/stomp_utils.py or something with a similar name would be a good place to put this function. Thoughts?

**Comment by bari12** [comment]
Making the stomp handling a common module is a good idea. We would have to include the different workflows where stomp is used though (Mostly hermes and kronos, and then all the minor workflows like the cache-consumer)

**Comment by ericvaandering** [comment]
I’d propose to add the simple refactoring to this PR and then open an issue for Hermes.  I don’t know how different it is.

**Comment by ericvaandering** [comment]
@bari12 This passes all the tests (after the rebase) and runs. Can we review and merge? (I can squash one final commit if everyone signs off, I don't want to trigger a new round of tests just for that).

**Review by bari12 — APPROVED** [review]

**Pull request merged**
