### PR TITLE
now VP call does not return anything if no VP replica created.

### PR DESCRIPTION
**Pull request by ivukotic**
replica: change in VP return #3257
------------------

It also returns nothing if the only regular replicas are on TAPE.

### CODE REVIEW

**Comment by bari12** [comment]
To me it looks good like this. @mlassnig should have a second look as the master-of-(list)-replicas though

**Review by mlassnig — APPROVED** [review]
this is fine, approving

**Comment by ivukotic** [comment]
Great. Thanks. So when can I expect to see this change in production?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bari12** [comment]
This will be part of the patch release 1.21.7 next week and go to integration testing on Tuesday next week. Production deployment is the week after.

**Pull request merged**
