### PR TITLE
REST API & Testing: Add Flask REST backend tests; Fix #1026 

### LINKED ISSUE #1026: add tests with flask rest backend on travis
Motivation
----------

It would be good to have the tests running against the flask backend in travis (with the mode allow failures) to expose the errors. With python 3,  it can be even better but would require to have fixed the syntax first.

### LINKED ISSUE #1817: Add functional Flask endpoints
Motivation
----------
The Flask API has problems with dealing exceptions when using JSON streaming. This should be fixed as it is essential for handling lot of data.

Modification
------------
See [documentation](http://flask.pocoo.org/docs/1.0/patterns/streaming/?highlight=stream) for implementing JSON streaming to change the Flask API.
Investigate how to deal with exceptions.

### PR DESCRIPTION
**Pull request by bziemons**
Remove paste test dependency and move all tests using either the Flask test client or the Werkzeug test client for the web.py application.
Additionally start using more pytest.fixtures leading to restructure of test code.

Fixes #1026

### CODE REVIEW

**Comment by bziemons** [comment]
@bari12 since the Flask tests are failing on *pr_releasetest* with authentication -- I am guessing #3960 was not cherry-picked to the 1.23 release branch?

**Comment by bari12** [comment]
It was, I think this must be failing due to another reason.

**Comment by bziemons** [comment]
Good to know. I will run the tests locally and look at the logs.

**Comment by bziemons** [comment]
@bari12 same as above, but replace #3960 with #3995 :D Do you want to merge this to 1.23? Since it is mostly about tests and the preparation work for the Flask API is already in 1.23, it would make sense. I could disallow unicode in the auth endpoint and then make an extra feature branch to enable it for 1.24+ in the Flask endpoint. Would that make sense?

**Review by bari12 — APPROVED** [review]

**Pull request merged**
