### PR TITLE
Clients: Replace obsolete links Fix #5084

### LINKED ISSUE #5062: Remove/Replace obsolete links from CLI commands in help messages
Motivation
----------
The following commands:
- rucio `list-file-replicas` [`--expression` `--rses`]
- rucio `list-rses` [`--expression` `--rses`]
- rucio `list-suspicious-replicas` [`--expression`]

display advise to follow http://rucio.cern.ch/client_tutorial.html#adding-rules-for-replication in order to get help about these options. That link does not point to any content at the moment.

Modification
------------
Remove obsolete link from help message and replace with useful information.

### PR DESCRIPTION
**Pull request by Carlosbogo**
Fixes PR #5084 by adding the changes requested by @joeldierkes, both in formatting and in code errors.

Closes #5062 by replacing the obsolete links to get help about CLI commands with working ones.

### CODE REVIEW

**Review by joeldierkes — CHANGES_REQUESTED** [review]
The header line of the commit (first line) is still somewhat undescriptive.
How about e.g. `Clients: Replace obsolete links Fix #5084` or `Clients: Replace obsolete links in command help Fix #5084`.

Feel free to change the commit message and update the current PR.

**Comment by joeldierkes** [comment]
Hint: Just changing the title does not change the commit.

**Comment by Carlosbogo** [comment]
Oh sorry, I'm still unsure how Git and Github relate to each other.
Can I change the commit directly from Github or do I have to do it locally using Git?

**Comment by joeldierkes** [comment]
As far as I know there is no way to alter a commit via the GitHub UI. You should do it locally and push the changes.

Use it as a practice session on how to alter a commit. 😅

**Comment by Carlosbogo** [comment]
Hopefully that's better. Again, sorry for the disturbance and thank you so much for taking the time to help.

**Review by joeldierkes — APPROVED** [review]

**Pull request merged**
