### PR TITLE
Release: python-memcached version

### LINKED ISSUE #4169: Python memcached package
`python3-memcached` had its last release in 2013, while `python-memcached` is newer -- removing `python3-memcached` and only using `python-memcached` seems to be the best option

_Originally posted by @bziemons in https://github.com/rucio/rucio/pull/4133#r532435018_

### PR DESCRIPTION
**Pull request by bari12**
Fixes #4169

### CODE REVIEW

**Comment by bziemons** [comment]
FYI: there is issue #4169

**Comment by bari12** [comment]
Perfect, thanks!

**Comment by bziemons** [comment]
I think `requirements.readthedocs.txt` needs to be edited as well? Or is that file finally obsolete?

**Comment by bari12** [comment]
It's (semi) obsolete. But that one I always update in the release preparation PR.

**Pull request merged**
