### PR TITLE
Add type annotations to replica and overloads for get_rse_attribute

### PR DESCRIPTION
**Pull request by rdimaio**
Part of #6588

### CODE REVIEW

**Comment by rdimaio** [comment]
Rebased in latest force-push

**Comment by rdimaio** [comment]
Addressed some typing failures in the latest forcepush.

Regarding this:

```
   - 1 errors with message """Expression of type "Sequence[UUID]" is incompatible with return type "list[str]"
                               "Sequence[UUID]" is incompatible with "list[str]"""".
    Candidates: line 2968
```

Will be fixed by https://github.com/rucio/rucio/pull/6930

**Comment by rdimaio** [comment]
Rebased in latest forcepush

**Comment by rdimaio** [comment]
Rebased and fixed type annotation change due to https://github.com/rucio/rucio/commit/05077338be21099e4a899691d1533ff31e013a9b in latest forcepush

**Comment by rdimaio** [comment]
For the current test failures:

- Codecov can be ignored
- Type check: refer to https://github.com/rucio/rucio/pull/6952#issuecomment-2242818067

**Review by bari12 — APPROVED** [review]

**Pull request merged**
