### PR TITLE
Clients: Protocol failover in download Fix #502

### LINKED ISSUE #502: Automatic protocol failover broken in rucio download
Motivation
----------
In version 1.14.7 `rucio download` always uses the same protocol from an RSE

Modification
------------

Expected behavior
-----------------
`rucio download` should fail over to a different protocol when the first one fails. Fail over used to work until version 1.14.5

### PR DESCRIPTION
**Pull request by nikmagini**
Clients: Protocol failover in download Fix #502

### CODE REVIEW

**Comment by nikmagini** [comment]
Hi all,

a comment: I noticed that there are two ways to choose the protocol for download; either the `force_scheme` argument of rsemanager.download; or through `rse_settings['read_protocol']`

I have used both, but please advise if it's preferred to use one or the other

N.

**Comment by TWAtGH** [comment]
Hi,
ok I think I finally understood how `rse_settings['<operation>_protocol']` is meant to be used.
It shouldnt store a full protocol description. It only stores the priority of the protocol that should be used. DEFAULT_PROTOCOL is 1 (0 means disabled).
It was used completely wrong in the downloader.
Edit: I'm not sure if these operation_protocol fields are usefull at all... The priorities are defined per protocol per domain but the operation_protocol fields don't have the domain information.

**Comment by bari12** [comment]
Yes, to force the protocol really `force_scheme` should be used. Manipulating the rse_settings is not the best way I would think. You could change (As Tobias described) the protocol priority in the rse_settings, but probably it is best to just run through with force_scheme.

**Comment by TWAtGH** [comment]
Actually without this commit you cannot just change the protocol prio in the rse_settings (at least not for download/upload) because these `<operation>_protocol` fields are ignored in `select_protocol`. I wonder if they are used elsewhere.

**Comment by bari12** [comment]
Yes, you are right, it would have to be changed in another part of the rse_settings (under the domains) - I think the `<operation>_protocol` is completely unused and should probably be removed. I will investigate this a bit in the afternoon. Anyway, how Nicolo is doing it now in this patch is fine and works.

**Comment by bari12** [comment]
Yes right, actually I think the `<operation>_protocol` is a dead setting and should not really be used.

**Comment by mlassnig** [comment]
can you deprecate `<operation>_protocol`? just rename the variable `deprecated_<operation>_protocol` and then we see if/what breaks

**Comment by bari12** [comment]
Yes we should. But lets do this in a different patch. I think the operation_protocol is a leftover from times before we had domain-support.

**Comment by nikmagini** [comment]
Ok I'll just use ‘force_scheme‘ and remove the ‘read_protocol‘ manipulation


Il mar 23 gen 2018, 09:34 Martin Barisits <notifications@github.com> ha
scritto:

**Review by TWAtGH — APPROVED** [review]

**Pull request merged**
