### PR TITLE
testing: fix vo-tests #3878

### PR DESCRIPTION
**Pull request by maany**
fixed the CLI for `votest_helper`.

### CODE REVIEW

**Comment by maany** [comment]
@joeldierkes @bari12 any idea why no checks are showing up for this PR? :O

**Comment by maany** [comment]
The checks are running in my account instead, interesting!
https://github.com/maany/rucio/actions/runs/1994187457

**Comment by joeldierkes** [comment]
We had the same problem in the rucio/documentation repo. Some actions weren't run at all...

**Comment by joeldierkes** [comment]
https://www.githubstatus.com/incidents/fpk08rxnqjz2
GitHub seems to be aware of some problems...

**Review by joeldierkes — APPROVED** [review]
LGTM
nit: The commit message could be more descriptive.

**Pull request merged**
