### PR TITLE
UI: Fix the favicon; Fix #4521

### LINKED ISSUE #4521: Fix favicon

### PR DESCRIPTION
**Pull request by mlassnig**

### CODE REVIEW

**Comment by bari12** [comment]
We should exchange the favicon itself though to the new icon. This is still the old one :-)

**Comment by bari12** [comment]
🛎️ ping on the favicon 😄

**Comment by bari12** [comment]
🏓

**Comment by mlassnig** [comment]
Hah! Look closely, I changed it: https://raw.githubusercontent.com/rucio/rucio/87afba99ce0c5f36bc24817ee5134c126b2cc59f/lib/rucio/web/ui/media/favicon.ico

**Comment by bari12** [comment]
My apologies 😆 Then please just rebase and this is good to go.

**Review by bari12 — APPROVED** [review]

**Pull request merged**
