### PR TITLE
Add python 3.10 to CI

### LINKED ISSUE #5145: Add python 3.10 tests to CI framework.
Motivation
----------
Python 3.10 is already out since October last year, with 3.10.1 being released a few days ago. This should be added to our test suite for validation.

Modification
------------
Add Python 3.10 to test matrix.

### PR DESCRIPTION
**Pull request by maany**
Fix #5145

This PR adds the new DIST ( stream8, stream9, fedora34, fedora35 ) and PYTHON (3.9, 3.10) to the autotest framework.

The available DIST, PYTHON test matrix is therefore

| | **stream8** | **stream9** |   **fedora34**  |**fedora35** |  centos7 | fedora32 | fedora 33 |
| ----- | -- | -- | -- |  -- | -- | -- | -- |
| 3.6    | x |      |    |    |   x  |    |    |
| 3.7    | x |      |    |    |   x  |    |   |
| 3.8    | x |      |    |   |     |   x  |    |
| 3.9    | x |  x  |  x  |    |    |    |   x |
| 3.10  | x |  x  |    | x  |    |   |    |

This matrix can run tests with all supported SUITE, RDBMS parameters.

We must shortlist the ( DIST, PYTHON, SUITE, RDBMS ) combinations we would like to run.

The `test_db::test_pooloverload` currently fails with Python3.10 and has been disabled in this PR for Python 3.10 environment. #6025 will address this later.

This PR also introduces the following new features which are part of upgrading the test framework itself:
1. Docker Multi-Stage builds for the new DISTs. 
2. Docker Buildkit
3. Using `virtualenv` to install python version and dependencies ( for caching the requirements stage and rebuilding images quicker )

### CODE REVIEW

**Review by maany — COMMENTED** [review]
This should be followed up with updating matrix_nightly.yaml

**Comment by mlassnig** [comment]
Instead of Stream, should we target the Alma releases?

**Comment by bari12** [comment]
We will, but this PR was made before the Alma announcement basically. So in the meanwhile I think we just go ahead with this.
I already discussed with Mayank, we will switch all stream to Alma and also at some point move our official containers from cc7 to alma.

**Comment by maany** [comment]
Already on it ;)

**Comment by maany** [comment]
@bari12 @mlassnig Added Alma8, Alma9. Rebased & squashed the commits. 

Final test matrix:
| | **alma8** | **alma9** |   **fedora34**  |**fedora35** |  centos7 | fedora32 | fedora 33 |
| ----- | -- | -- | -- |  -- | -- | -- | -- |
| 3.6    | x |      |    |    |   x  |    |    |
| 3.7    | x |      |    |    |   x  |    |   |
| 3.8    | x |      |    |   |     |   x  |    |
| 3.9    | x |  x  |  x  |    |    |    |   x |
| 3.10  | x |  x  |    | x  |    |   |    |

After merging this, open PRs would need a rebase to be built against the new test suites.

**Comment by bari12** [comment]
Sorry Mayank, I merged the one PR from @ThePhisch 
Please rebase :-)

**Review by bari12 — APPROVED** [review]

**Pull request merged**
