### PR TITLE
Testing: Re-activate integration tests. #2311

### PR DESCRIPTION
**Pull request by rcarpa**
The dependency commit was merged. Only run the test on integration, as it needs XRD containers to be set

### CODE REVIEW

**Review by bziemons — DISMISSED** [review]

**Comment by bari12** [comment]
Please rebase to updated `master`, otherwise GTG

**Review by bziemons — DISMISSED** [review]

**Review by bziemons — DISMISSED** [review]

**Comment by bziemons** [comment]
the integration testing just broke @tbeerman

**Comment by rcarpa** [comment]
What do you mean. This one is not yet merged  `¯\_(ツ)_/¯`

**Comment by bziemons** [comment]
I mean the `dev/Dockerfile_py3` from the containers repo was moved and the integration tests here in this repo depended on that

**Comment by tbeerman** [comment]
the previous `dev/Dockerfile_py3` is now the main `Dockerfile`. I removed the old one (it was anyway not working anymore) and thought I just move the py3 file. Didn't know that these tests depend on it. I can add it back but would it be possible to fix the tests instead?

**Comment by rcarpa** [comment]
Let me see if I can do it in a quick commit. I'm already doing rebase and tests all the day :(

**Comment by bziemons** [comment]
I agree we should fix this in this repo. Could someone please make the change here: https://github.com/rucio/rucio/blob/089f6778f15c36c027622d3afa9ece569d6ebf57/.github/workflows/integration_tests.yml#L40-L43

**Comment by tbeerman** [comment]
@mlassnig also just fixed it in https://github.com/rucio/rucio/pull/4465

**Pull request closed without merging**
