### PR TITLE
Docker: Binding to specific IPs #4782

### PR DESCRIPTION
**Pull request by rak108**
This PR is in relation to issue #4782

### CODE REVIEW

**Comment by rcarpa** [comment]
Love it. Hope it works with podman. @bziemons , any opinion ?

**Comment by bziemons** [comment]
The title of the PR doesn't really explain what is actually happening, but yes: I prefer binding to 127.0.0.1 only and it works with podman. I wanted to make this change before, but it was decided not to do it, because some wanted to reach the services (rest api, web-ui, database, ...) from outside the own host... not sure if that is still a requirement though

**Comment by rcarpa** [comment]
Weeeell, i'd say that those who want to do nasty things can maintain their own local config :)

**Comment by mlassnig** [comment]
Well, at least we need it for the SSH container. For the rest, we should apply some good old democracy :-)

**Comment by rak108** [comment]
@mlassnig ah alright, so should I close this PR?

**Comment by mlassnig** [comment]
I'm voting for 127.0.0.1 on all of them :-)

**Comment by bziemons** [comment]
I think it is decided then. There is no opposing vote ;)

**Review by mlassnig — APPROVED** [review]

**Comment by bari12** [comment]
🥳

**Pull request merged**
